### ISSUE TITLE
gopls consumes permanent high CPU usage

### ISSUE THREAD

**Issue by Klaus-Tockloth** [golang/vscode-go#1041]
### What version of Go, VS Code & VS Code Go extension are you using?
- go version go1.15.6 darwin/amd64
- golang.org/x/tools/gopls v0.6.0
- Visual Studio Code Version: 1.52.1
- Go for Visual Studio Code v0.19.1

### Share the Go related settings you have added/edited

<img width="974" alt="Bildschirmfoto 2020-12-17 um 09 01 14" src="https://user-images.githubusercontent.com/5493128/102459986-a8464d00-4046-11eb-8bfb-4703430ae33a.png">

<img width="975" alt="Bildschirmfoto 2020-12-17 um 09 01 38" src="https://user-images.githubusercontent.com/5493128/102460012-b1cfb500-4046-11eb-95f2-71664f791237.png">

### Describe the bug
gopls consumes after VS-Code start permanent high CPU usage (and does a lot of internet communication). VS-Code nearly unusable.

<img width="462" alt="Bildschirmfoto 2020-12-17 um 08 53 53" src="https://user-images.githubusercontent.com/5493128/102460133-d75cbe80-4046-11eb-8115-36de3db0e9aa.png">

gopls (server) log attached.

[gopls-server.log](https://github.com/golang/vscode-go/files/5707832/gopls-server.log)

**Comment by hyangah** [comment]
VSCode was opened from the `GOPATH/src` directory. 
@stamblerre What is the current best practice in this case?

@Klaus-Tockloth Are all the packages under the `GOPATH` related? Is it possible to open only repo directories you intend to actively work on?

**Comment by Klaus-Tockloth** [comment]
> Is it possible to open only repo directories you intend to actively work on?

The problem is gone, if I reduce my workspace.

Large Workspace with 'gopls' CPU consuming problem:
<img width="330" alt="Bildschirmfoto 2020-12-17 um 16 57 08" src="https://user-images.githubusercontent.com/5493128/102512057-dac56980-4089-11eb-860c-c761e7b8c118.png">

Small Workspace without  'gopls' CPU consuming problem (workspace reduce to folder 'klaus'):
<img width="331" alt="Bildschirmfoto 2020-12-17 um 16 59 21" src="https://user-images.githubusercontent.com/5493128/102512097-e6b12b80-4089-11eb-8c5a-63a07b6cca50.png">

Looks like a workaround ... thanks for pointing to this.

**Comment by stamblerre** [comment]
This case is specifically mentioned here: https://github.com/golang/go/issues/36899. I know this issue is not very discoverable, but its contents will eventually be merged into our documentation. Opening your entire `GOPATH/src` is not actively supported, but you can use our new [directoryFilters](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#directoryfilters-string) to exclude certain directories from analysis by `gopls`.

**Comment by hyangah** [comment]
@Klaus-Tockloth Great to hear that narrowing down the workspace scope made improvement. In general, Go is moving toward modules mode instead of GOPATH mode (eventually, GOPATH will be deprecated), I think it's time to consider the new module-based workflow.

@stamblerre thanks for the pointer. I updated https://github.com/golang/vscode-go/issues/934 to include the workspace setup in the documentation. Let me close this issue and let's follow up in the documentation improvement work.
