### ISSUE TITLE
gopls: automated issue report (opt out)

### ISSUE THREAD

**Issue by wenqvip** [golang/vscode-go#1050]
gopls consumes many memories and runs slowly.
I will wait for serval seconds or even one minutes to let it skip to definition or references. It really slow down my work on my mac book pro.

**Comment by stamblerre** [comment]
@wenqvip: As per https://github.com/golang/vscode-go/issues/1037, `gopls` will soon be enabled by default in the VS Code Go extension. It is more feature-rich and better supported, so we'd be happy to help you investigate the issue so that you can use `gopls`.

If you would like to troubleshoot the problem, please try enabling `gopls` again and share your logs: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs. We can try to understand the problem and advise on how to resolve it.
