### ISSUE TITLE
gopls unable to get metadata for modules that are `replaced` in go.mod 

### ISSUE THREAD

**Issue by nveenjain** [golang/vscode-go#1105]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.15.2 darwin/amd64
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- golang.org/x/tools/gopls v0.5.0
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.52.1
- Check your installed extensions to get the version of the VS Code Go extension
	- v0.21.0
- Run `go env` to get the go development environment details
	- (Work machine)

### Share the Go related settings you have added/edited

Added     
```json
{
    "go.formatTool": "gofmt",
    "go.useLanguageServer": true,
    "go.lintOnSave": "file"
}
```

### Describe the bug
We are using go mod replace to replace some local modules. (https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/), these modules were getting recognized in v0.20.0 but are not recognized now after i enabled languageServer in v0.21.0 

### Steps to reproduce the behavior:
1. Replace any go module to point to local instance (name doesn't have a valid domain for eg: `naveen/utls` points to `../../utils-go/utils` package  
2. Import the replaced module
3. Imported module isn't recognized

**Comment by nveenjain** [comment]
Along with this, some struct that isn't declared in the same file also doesn't work. (It doesn't recognize the struct declared in some other file)

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by hyangah** [comment]
AFAIK, gopls should work with 'replace' unless the replaced module exists outside the workspace. (https://github.com/golang/go/issues/40812 - vscode does not allow to watch outside of the workspace) 

@nveenjain if you are having the issue even though the local instance is within the workspace, please share the log @stamblerre requested. Otherwise, please follow golang/go#40812 for the progress and the workaround.

**Comment by nveenjain** [comment]
Hey @stamblerre , sorry for late response, didn't receive the mail for your reply! Here are the logs:

```
[Error - 2:20:00 PM] 2021/02/11 14:20:00 errors loading workspace: You are outside of a module and outside of $GOPATH/src.
If you are using modules, please open your editor to a directory in your module.
If you believe this warning is incorrect, please file an issue: https://github.com/golang/go/issues/new.
	snapshot=26
	directory=file:///Users/naveen/Documents/workspace/demoApp

[Error - 2:20:00 PM] 2021/02/11 14:20:00 command-line-arguments: no dep handle for demoApp/utils/models: no metadata for demoApp/utils/models
	snapshot=26
```
I've opened my editor in workspace which is a monorepo, where root directory of workspace will have different folders signifying different subprojects, and hence i don't have any go.mod in root directory of workspace. 
I've my demoApp in a separate folder, not in $GOROOT or in $GOPATH/src, here is how the project looks like
I define multiple packages in demoApp/go/
each package have their go.mod file, in one of go.mod file, I replace demoApp/utils/models to ../utils/models but this errors out.

**Comment by hyangah** [comment]
Thanks @nveenjain. Currently gopls does not support the layout by default. Here are a couple of workarounds you may want to try out:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules

Let us know if the experimental ['Workspace module'](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#workspace-module-experimental) works for you - since we are currently evaluating this idea.

**Comment by stamblerre** [comment]
Closing as this has been in the WaitingForInfo state for a few months.
