### ISSUE TITLE
Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by andhet** [golang/vscode-go#1177]
This is relating to the closed issue #222.
To quote @meysholdt
> Hi,
>
>congrats on moving this extension to the Go-Team!
>
>Could you also publish the golang.Go extension on https://open-vsx.org/ ?
>
>This would make it much easier to use this great extension in project such as
>
>  * gitpod.io
>  * theia-ide.org
>  * vscodium.com
>   * code-server

>because the ToS doesn't allow those projects to obtain the extension from Microsoft's marketplace:

>>Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use >>Marketplace Offerings with Visual Studio Products and Services.
 
The presented solution to keep the "latest" branch up to date, didn't work very well so a issue [[golang.go] latest version is not being published](https://github.com/open-vsx/publish-extensions/issues/200) "open-vsx/publish-extensions" was created. During the discussion a commit was created changing the former behaviour to use the vscode-go latest branch to publish new versions to open-vsx.org and to use a fix version instead. Of course this means that every version must be manual updated in the open-vsx/publish-extensions project, which is not an ideal solution.
During the discussion @jankeromnes said:
>That's why it's much better when the extension's owners/maintainers can publish to OpenVSX directly. (It's as simple as setting >up a [OVSX_PAT](https://open-vsx.org/user-settings/tokens) token and running `npx ovsx publish` -- no dependencies required).
>But since this wasn't set up yet for golang.go, we took over the publishing in the interim, using this repository. 

So I would ask if you be so kind to publish directly to open-vsx.org in the future.

**Comment by hyangah** [comment]
Thanks for pinging us. We will resume updating the latest branch.

The latest extension requires vscode API compatible with vscode 1.46 or newer engine. End of last year, we noticed some of theia-ide based services couldn't use latest versions. https://github.com/golang/vscode-go/issues/1038
We will resume updating the` latest` branch.

After reviewing the setup process and long-term maintenance cost for publishing open-vsx directly, we decided to stay with the current setup for now. 

The vsix files are available from the release page too.

**Comment by andhet** [comment]
Thanks for your answer. 
I will try to clarify if "open-vsx/publish-extensions" will go back to use your latest branch again or will keep maintaining a fix version, which wouldn't make it necessary to keep the latest branch up to date. (At least not from their side.)

**Comment by jankeromnes** [comment]
Thanks! Please feel free to make this decision.

In general for this repository, we prefer re-publishing the latest official `.vsix` release, because that's less "risky" than cloning the extension repository and trying to rebuild/repackage the extension (where there is a chance to mess up and upload a broken extension binary, especially since we manage a significant number of extensions and don't have much time to look deeply into each extension's packaging process, or even test the uploaded extension).

I guess this means that, if we're confident that we can always publish a 100% working extension but checking out the `latest` branch (without updating the build instructions, even months from now), then it's okay to publish from `latest`. Otherwise we re-publish an official `.vsix`, but occasionally need to update to a newer version (manually or automatically).

**Comment by hyangah** [comment]
@jankeromnes and @andhet, Thanks!

I prefer scraping from the release page instead of the latest branch - it's set up that way because I thought open-vsx could only  watch a tag or a branch back then. Open-vsx is the only user of the branch `latest` AFAIK (other non-vscode extension consumers already scrape our release branch). It sounds like open-vsx can republish the latest official .vsix, so can we delete the latest branch?

**Comment by andhet** [comment]
@hyangah 
Yes, we'll find another solution than using the latest branch. So feel free to delete it.

**Comment by jankeromnes** [comment]
> Open-vsx is the only user of the branch `latest` AFAIK

For what it's worth, OpenVSX already scrapes GitHub Releases and doesn't use the `latest` branch:

https://github.com/open-vsx/publish-extensions/blob/618b2ff140622e3e9ce976bf477c19c65a09a31f/extensions.json#L548-L552

> (other non-vscode extension consumers already scrape our release branch)

Interesting, which non-vscode extension consumers do you have in mind?

I know that VSCodium, Gitpod.io, Theia, Eclipse Che and others all use OpenVSX directly.

**Comment by hyangah** [comment]
Sounds good. Deleting the `latest` branch.

Last time I checked (Dec 2020), gitpod.io had ms-vscode.go extension embedded in the default container and users weren't able to use ours. That should be fixed now. Code server has their own marketplace. VSCodium uses openvsx.

And, due to https://github.com/eclipse-theia/theia/issues/8752, currently I recommend v0.20.x or earlier for theia-based IDEs.
