### ISSUE TITLE
lint: Do not highlight comments of exported types if they don't start with type name.

### ISSUE THREAD

**Issue by DmitriyVTitov** [golang/vscode-go#1257]
I'm always frustrated when I have to use comments of exported type starting with type name. I write comments in Russian so it just doesn't look good with English word at the start. For example I have a good comment:
![image](https://user-images.githubusercontent.com/38575605/109395624-6dae3a00-793e-11eb-970c-160f17b502b1.png)
But it's considered a problem.

I think we shouldn't highlight comments if it's not English. I don't think Go authors meant languages others from English when they recommended comments style.

**Comment by DmitriyVTitov** [comment]
Also I think package comments do not have to start with `Package packagename ...`. It looks ugly with non-english comments.

**Comment by hyangah** [comment]
@DmitriyVTitov The diagnostic comes from the current default lint tool (`golint`). Try `"go.lintTool": "staticcheck"` - which doesn't seem to have [the corresponding style rule](https://staticcheck.io/docs/checks#ST1021) disabled by default.

FYI We plan to switch the default lint tool to staticcheck soon because the golint is deprecated.

**Comment by DmitriyVTitov** [comment]
@hyangah I've switched lint tool ti staticcheck and this rule does not apply so it's not enabled in default configuration (you must be misprinted. Sunce it's going to be the default linter I think we may close this isuue.
Thanks!
