### ISSUE TITLE
support folding of #region comments

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#134]
As described in https://github.com/microsoft/vscode-go/issues/3249, the folding of region comments stops working when `gopls` is enabled.

We have an upstream issue logged in VS Code. see https://github.com/microsoft/vscode/issues/98099. If it is determined that VS Code should respect results from multiple folding providers, then we can expect VS Code to fix the issue. Otherwise, it needs to be decided if `gopls` should be updated to include folding of region comments

---
EDIT(2023/02/28) - Gopls will not add this editor-specific hack. Instead, our current recommendation is to use the indentation-based folding strategy.

```
"editor.foldingStrategy": "indentation"
``` 

This indentation-based folding (vscode default) supports `#region ...  #endregion`.  For example,

```
// Summary
// #region Details

doComplexTask()

// #endregion
```

![Screenshot 2023-02-28 at 9 49 28 PM](https://user-images.githubusercontent.com/4999471/222032611-78c1642b-2dd5-48ce-9f45-c9a53c0d6678.png)

**Comment by stamblerre** [comment]
Spent a bit more time looking at this. It seems like these `#region` commands are defined per-language: https://code.visualstudio.com/docs/editor/codebasics#_folding.

@ramya-rao-a: Where are they defined for Go, and how do they work without the language server?

**Comment by ramya-rao-a** [comment]
They are probably defined upstream in VS Code

See https://github.com/microsoft/vscode/blob/master/extensions/go/language-configuration.json#L31-L35

**Comment by hyangah** [comment]
I think I figured it out finally. I wish vscode API documentation described this clearly.

The default folding (indentation folding, `#region..#endregion`) offered by vscode is disabled if any regular folding provider returns folding results. `gopls` serves folding ranges, so that disables the default folding (if I disable the folding from the language server, I observe the default folding kicking in). See the background here:

https://github.com/microsoft/vscode/issues/50991#issuecomment-394476116 
https://github.com/microsoft/vscode/issues/47404

This extension itself does not implement any custom folding provider, so always the default folding from vscode is applied unless the language server is enabled. 

If the default folding is preferred, the following setting will do the job.

```
"editor.foldingStrategy": "indentation"
```

Implementing our folding provider to support `#region...#endregion` when the language server is enabled is one option. 
https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider

Another option is to use another extension designed for explicit folding support.

**Comment by hyangah** [comment]
We can offer one more folding provider, but resolving conflicting or overlapping folding ranges from different providers is not trivial. According to the `registerFoldingRangeProvider` API doc, the following heuristic is applied.

```
Multiple providers can be registered for a language. In that case providers are asked in parallel and the results are merged. If multiple folding ranges start at the same position, only the range of the first registered provider is used. If a folding range overlaps with an other range that has a smaller position, it is also ignored.
```

I am afraid this can potentially lead to confusion. 
For Go, I think `"editor.foldingStrategy": "indentation"` will work reasonably in most cases except some cases like `switch` statement. So, for users who want `#region..#endregion`, my recommendation is to set the indentation-based folding strategy.

**Comment by hyangah** [comment]
There are folding range provider extensions that support this feature. Even some offer customization around the marker keywords. I confirm VS Code tries its best to merge foldings from multiple extensions, and there are various editor settings to adjust folding policies and providers.

Closing.
