### ISSUE TITLE
debug: Disable the "Failed to continue: check debug console" pop-up

### ISSUE THREAD

**Issue by acornyname** [golang/vscode-go#1375]
Can you add an option to disable the "Failed to continue: check debug console" pop-up that was enabled in recent versions of the extension? It really interrupts my workflow to have to close this every time there's an error in my code.

**Comment by hyangah** [comment]
@acornyname Can you provide how to reproduce the issue? Or enable the tracing/logging following the instruction [here](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enable-logging) and share the last part? 

As you can see from the [commit history](https://github.com/golang/vscode-go/commits/master/src/debugAdapter) there were not many changes in the existing debug adapter codebase recently.

**Comment by acornyname** [comment]
Anytime my code doesn't run (because there was a mistake etc. in it) the debugger pops up with a message that says failed to continue and plays a system notification, I ended up disabling system sound until I figured out how to rollback the go extension about a year because of it. 

I was just wondering if you could add an option to the extension to disable this pop-up, cause there doesn't seem to be one.

I've attached an image of the error in question. 

[https://i.redd.it/vkbr5o65xal61.png](url)

**Comment by hyangah** [comment]
Thanks for sharing the screenshot @acornyname  
That has been working like this for a while. See the discussion about use of modal popup for compilation errors, back in 2018. 
https://github.com/microsoft/vscode-go/issues/1644

![Screen Shot 2021-03-25 at 4 46 46 PM](https://user-images.githubusercontent.com/4999471/112541399-bb756100-8d89-11eb-8c4c-e30fbc56d12e.png)

In your specific case shown in the screenshot, I am guessing it's related to upgrade to go1.16. With go1.16, `go.mod` file is necessary unless you are operating in GOPATH mode. Run `go mod init <your module name>` in the project root to create `go.mod` file.

ps. You can install old versions of any extension by choosing "Install Another Version.." from the extension view

**Comment by db81** [comment]
I concur with @acornyname that this is quite annoying. The modal happens every time delve exits with non-zero code, and the most common reason for that is a syntax error in your code.

I get the idea in https://github.com/microsoft/vscode-go/issues/1644#issuecomment-509942632 that if debugger fails to launch you're supposed to treat it as a serious error. However in practice this means you'll get the modal every time you press F5 with a syntax error, that's a frequent situation in one's workflow and makes the experience less seamless.

It should be possible to check whether delve quit because of a syntax error or a different reason and suppress the modal in the former case.

Here's a snippet for you to run in bash if you want to disable the modal (if you're using VS Code with WSL2, run it in wsl terminal):
```bash
sed -i -e '/Failed to continue: Check the debug console for details/d' ~/.vscode{,-server}/extensions/golang.go-*/dist/debugAdapter.js
```

**Comment by sommerper** [comment]
> ```shell
> sed -i -e '/Failed to continue: Check the debug console for details/d' ~/.vscode{,-server}/extensions/golang.go-*/dist/debugAdapter.js
> ```

Thank you! This was driving me crazy.

In my case on MacOS it was
`sed -i -e '/Failed to continue: Check the debug console for details/d' /Users/USERNAME/.vscode/extensions/golang.go-0.26.0/dist/debugAdapter.js'/Failed`

**Comment by polinasok** [comment]
@hakim @suzmue What do you think about just sending a terminated event and either a launch success response or no response. Either way the client is supposed to trigger disconnect as soon as it sees the terminated event. Theere will be no pop-up and the error will still be in the Debug Console.

**Comment by hyangah** [comment]
As long as the it is future-proof (so the future release of VS Code doesn't change the behavior surprisingly), either is fine. But let's hear VS Code team's thought on your idea. Thanks for updating the upstream issue!

**Comment by polinasok** [comment]
@acornyname @sommerper @ db81 We have convinced vscode to give us a way to control the modal pop-up instead of always triggering it when there is an error. We will be updating the adapter shortly to take advantage of this for supressing the modal alert for build errors, so the improvement is there when the new version of vscode is released.

**Comment by polinasok** [comment]
With an updated version of dlv-dap the pop-up should now be suppressed:
![image](https://user-images.githubusercontent.com/51177946/135025348-6895dae2-70a3-40a5-a067-a5156300bcfb.png)

**Comment by db81** [comment]
Thanks for pushing this through.

**Comment by joehonton** [comment]
Yeah! Relief.
