### ISSUE TITLE
debug: disable showing global variables by default

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#138]
As being discussed in https://github.com/microsoft/vscode-go/issues/2210, the feature of showing global variables when debugging requires calling `ListPackageVars` which is expensive in many cases. The setting `showGlobalVariables` was introduced for the very same reason of this feature being expensive.

This issue is to consider this setting to have the default value of `false` instead of `true` to improve the out of the box experience.

**Comment by hyangah** [comment]
@polinasok Since you are currently looking into the variables listing - what do you think about disabling this by default in the next release? The original issue had ~39 upvotes. I am leaning toward to accepting this.

I'd feel more comfortable if users can turn on/off the global variable listing on demand. Are you aware of any knobs that dynamically control the scope of variables in an active session?

**Comment by polinasok** [comment]
There is no option currently to control this dynamically. We could create such an option, so variables are loaded only if the user expands the Global scope (which is like a made-up variable in the backend). It could be handled similarly to how we would autoload more variable data that was not loaded right away (this is already done for interfaces,  but not other data in vscode-go).
