### ISSUE TITLE
debug: don't show "Unable to eval expression" error message already under WATCH

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#143]
_From https://github.com/microsoft/vscode-go/issues/3227 by @kzhui125_

<img width="470" alt="1" src="https://user-images.githubusercontent.com/11925432/81276655-e4173e00-9085-11ea-8589-d37f4ae63ac2.png">

In other extensions such as python, if you eval an expression which produces error, the error is only shown in "WATCH".

But in VSCode go extension, the message box is shown, which is not needed.

And the message box pop up again and again, which has very bad experience.

There are cases when you put a variable in watch, but not available in current debug point.

**Comment by ramya-rao-a** [comment]
I don't see how we can communicate the error to VS Code if we don't send the error response as shown in https://github.com/microsoft/vscode-go/blob/12fd44a26788fb285207a3482dbb21d486b9d8b9/src/debugAdapter/goDebug.ts#L1332

If we remove that, then the watch pane would simply say "not available".
But another place to evaluate symbols is the debug console which would not say anything if we don't send an error response.

**Comment by ramya-rao-a** [comment]
From https://github.com/microsoft/vscode-go/issues/3227#issuecomment-636033490 by @hyangah:

> My proposal is not to drop the error response, but to find another way (is it possible to formulate it as a regular response, but with some indication on error?). Does anyone know how python extension handles this?

**Comment by polinasok** [comment]
My first thought was the same as @hyangah's: instead of [sending ErrorResponse](https://github.com/microsoft/vscode-go/blob/12fd44a26788fb285207a3482dbb21d486b9d8b9/src/debugAdapter/goDebug.ts#L1332), send back successful EvaluateResponse, setting the result of the expression to the error message. Quick test of this alternative code snippet (which could be used in case of `args.context=='watch'`)
```
response.body = {result: err.toString(), variablesReference: 0};
this.sendResponse(response);
```
yielded expected results: the error appeared in the Watch section without the pop-up.

Request:
```
{"command":"evaluate","arguments":{"expression":"bbbb==1","frameId":1000,"context":"watch"},"type":"request","seq":9}
```
Response before:
```
{"seq":0,"type":"response","request_seq":9,"command":"evaluate","success":false,"message":"Unable to eval expression: \"{e}\"","body":{"error":{"id":2009,"format":"Unable to eval expression: \"{e}\"","variables":{"e":"could not find symbol value for bbbb"},"showUser":true}}}
```
Response after:
```
{"seq":0,"type":"response","request_seq":9,"command":"evaluate","success":true,"body":{"result":"could not find symbol value for bbbb","variablesReference":0}}
```
But this seems like the wrong way to go, given the spec.

**Comment by polinasok** [comment]
Now lets look into what [vscode-python](https://github.com/Microsoft/vscode-python) does, given that it has the desired behavior without the pop-up. Its [debug adaptor](https://github.com/microsoft/vscode-python/blob/master/src/client/debugger/debugAdapter/main.ts) appears to forward things over to [PTVSD](https://github.com/microsoft/ptvsd), which also uses DAP. And PTVSD sends back neither a successful EvaluateResponse nor a full-fledged ErrorResponse, but [something in-between](https://github.com/microsoft/ptvsd/blob/6be0e232eabd74b4963c01c289cab3f81b94ef1c/src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py#L934) - an EvaluateResponse with the body set to EvaluteResponseBody and not ErrorResponseBody while success and message fields are set as they would be in an ErrorResponse. 

Turning on logging with `"logToFile": true` in launch.json, I get logging from the newly released debugpy, which is consistent with the same approach:
```
Server[1] --> {
                 "pydevd_cmd_id": 502, 
                 "seq": 40, 
                 "type": "response", 
                 "request_seq": 15, 
                 "success": false, 
                 "command": "evaluate", 
                 "message": "NameError: name 'abcdef' is not defined", 
                 "body": {
                     "variablesReference": 0, 
                     "presentationHint": {}, 
                     "result": "NameError: name 'abcdef' is not defined"
                 }
             }
``` 
This is then forwarded up the adaptor chain, stripping the EvaluateResponseBody and turning this into a proper ErrorResponse (since `success==false`):
```
Client <-- Adapter:
{
    "seq": 19,
    "type": "response",
    "request_seq": 11,
    "success": false,
    "command": "evaluate",
    "message": "NameError: name 'abcdef' is not defined"
}
```
But the big difference with Go is that the optional error Message in the body is not set at all. 
Upon further inspection, I noticed that the body has a field showUser, which is set to true in the vscode-go response. I think that's the key here and we just need to set it to false in case of 'watch' context. 

I will put together a quick PR tomorrow.
