### ISSUE TITLE
debug: warn users when debugging optimized binaries

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1471]
From https://github.com/golang/vscode-go/discussions/1446 by @JadenSimon 

Delve allows users to debug optimized binaries, however, when using the Delve client it will warn you that the function is optimized after hitting a breakpoint. This means the user is not confused when local variables are not what they expect (i.e. missing or invalid). The Go extension's DA makes no attempt at alerting the user that they might be debugging an optimized binary, causing a lot of confusion when debugging does not work as expected. This is especially true when remote debugging, as it may be up to an external process to do the compilation.

@polinasok @suzmue `Optimized` bit is a property of [Function](https://github.com/go-delve/delve/blob/c5d58f494a266d9f95bf597bce894bd8d9204a65/service/api/types.go#L200). Is there any good way to surface this in UI/DAP?

**Comment by suzmue** [comment]
We could surface this in the variables pane since this would be the feature that is most affected by the optimized function. 

An option:

Before:
![Screen Shot 2021-05-05 at 12 21 07 PM](https://user-images.githubusercontent.com/6634754/117175082-6ff89e80-ad9c-11eb-9c9e-a1dd941cfde2.png)
After:
![Screen Shot 2021-05-05 at 12 21 15 PM](https://user-images.githubusercontent.com/6634754/117175092-72f38f00-ad9c-11eb-81d9-a7e9f56136b8.png)

We could also send a warning message to the Debug Console, but this may be less visible.

**Comment by polinasok** [comment]
A pop-up would be ideal, but I don't know of a way to trigger it other than an error response, which wouldn't apply here. I agree that logging to Debug Console might get lost and something more visible would be helpful. Labeling variable scopes is pretty clever.

**Comment by suzmue** [comment]
This has now been implemented in delve dap, by adding the annotation to the scope name:

<img width="552" alt="Screen Shot 2021-06-07 at 5 35 57 PM" src="https://user-images.githubusercontent.com/6634754/121090597-d404ed00-c7b6-11eb-83ef-0c3f81dd4560.png">

@JadenSimon @polinasok @hyangah Is this sufficient? If you think this takes care of the problem we can close this issue.
