### ISSUE TITLE
debug: Go equivalent of JavaScript Debug Terminal in VS Code

### ISSUE THREAD

**Issue by haroldadmin** [golang/vscode-go#1534]
**Is your feature request related to a problem? Please describe.**
Debugging a Go program that requires command line arguments is difficult in VS Code. You need to create a launch configuration with your arguments and then run the config. This process is complicated, time consuming, and requires changes to the launch config whenever you need to change the command line arguments.

Compare this situation to VS Code's "JavaScript Debug Terminal" feature which automatically attaches the debugger to any node process launched from that terminal. It negates the need to create launch configs for debugging a program with command line args. 

**Describe the solution you'd like**

Something like a "Go Debug Terminal" which automatically attaches the debugger to any go process launched from that terminal.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by polinasok** [comment]
@haroldadmin Thank you for your report. I am not familiar with how this works with JavaScript. Could you please elaborate how you would like this to work for Go programs? Would like to be able to launch your program with the needed command-line arguments from the command-line and then have the debugger attach to it? Or would you like to launch the debugger from the command-line, which will in turn launch the program for you, and then have the editor connect to that debugger instance? Do I understand correctly that the current `"Attach to local process"` and `"Connect to server"` launch configurations are not sufficient because you must enter the process id or the port manually (as opposed to being automatically derived from the integrated Terminal inside of the editor window)? I think currently the closest approximation to what you are looking for would be to start dlv debugger from the command-line with a predefined port:
```
dlv debug [package] --headless --listen=:12345 -- [command-line args]
```
Then in your launch.json configuration use:
```
{
            "name": "Connect to server",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "port": 12345,
            "host": "127.0.0.1"
},
```
Would this be sufficient for your needs for now?

Please note that we are working on a replacement debug adapter [dlv-dap](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md). It does not yet support program flags on the command-line, so the above would only work with the legacy adapter until we implement this feature in dlv-dap.

**Comment by haroldadmin** [comment]
@polinasok
> Would like to be able to launch your program with the needed command-line arguments from the command-line and then have the debugger attach to it?

This is exactly what I'm looking for.

> Do I understand correctly that the current "Attach to local process" and "Connect to server" launch configurations are not sufficient because you must enter the process id or the port manually (as opposed to being automatically derived from the integrated Terminal inside of the editor window).

Yes, you're correct.

> I think currently the closest approximation to what you are looking for would be to start dlv debugger from the command-line with a predefined port: `dlv debug [package] --headless --listen=:12345 -- [command-line args]`

I didn't know I could launch `dlv` with command line args manually, thanks for sharing this. Having this procedure be automated would be great, though.

---

I created a small clip to illustrate how the JavaScript debug terminal works in VS Code. I hope it helps:

https://user-images.githubusercontent.com/24315306/120597666-f61f0800-c462-11eb-9bdd-e8b669049921.mov

**Comment by hyangah** [comment]
@haroldadmin If your program binary has a unique name, another alternative is to utilize the usual `attach` mode and provide the binary name as the `processId` in the launch configuration. In the following example, you can see that the debugger is attached automatically because the launch process id is configured to be the specific binary (regardless what process id it gets) 
```
 {
            "name": "Attach to Process",
            "type": "go",
            "request": "attach",
            "mode": "local",
            // Attach to the process whose executable name is 'mybin'
            "processId": "mybin",
            // Use the new debug adapter.
            "debugAdapter": "dlv-dap"
   }
```

https://user-images.githubusercontent.com/4999471/121082457-1f65ce00-c7ac-11eb-9e96-98f915ff9650.mov

[This pick-process-by-name feature](https://github.com/golang/vscode-go/blob/570a0a4e2be12da4953dab7e8ac3adc82996ca74/src/pickProcess.ts#L23) is currently available in the [Nightly version](https://github.com/golang/vscode-go/blob/master/docs/nightly.md) and works more reliably with [the new dlv dap mode debug adapter](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md).
 
You will still need to configure the launch.json to specify the `processId` attribute. However, once set up, you can run quickly by pressing `F5`. 

--
But still the zero-configuration debug capability is something we look into further.

It looks like JS debugger provides this feature by telling the Node.js to require a special bootloader script before running your program by setting `NODE_OPTIONS` environment variable or utilizing Node.js's `--inspect` flag. That way, before the program runs, special debug communication channels (IPC, network socket, ..) is setup and VSCode & JS debug adapter can auto-attach and inspect your program using the inspector protocol.  

Go is a compiled language, not interpreted language. There is no "`node`" equivalent of command. The binary is not easily distinguishable from other binaries users would run or keep running from the terminal. (e.g. `go`, `dlv`, ...)  One may think we can unconditionally assume any binary running from a dedicated integrated terminal can be a debug target, but I am not sure if that's desirable.

Note that for complete debugging experience, users need to compile the target binary with appropriate flags to disable some optimization and avoid stripping necessary debug info away. This is a common mistake many of the delve users made before. If we just let users launch any arbitrary go program from the terminal, and pretend we can debug the binary, it will create confusion in the future. `dlv debug` or `dlv test` takes care of the build process, so if we implement the auto-attach feature more like js debugging, I think we need to consider utilizing them rather than asking users to launch any binary and trying to attach. I agree `dlv debug --headless --listen=:port` seems a bit long though. Some options in my mind:

  * Packaging the extension with a small wrapper program (e.g. `debugme`) so users can run the program with
      'debugme myprogram args ...` 
  * Ask users to at least run the program with `dlv debug --headless` and figure out the open port (by default delve picks the port for headless mode).
  * Convince dlv to get port from the environment variables.

References
* [VSCode debug autolaunch extension](https://github.com/microsoft/vscode/blob/main/extensions/debug-auto-launch/src/extension.ts)  
* [`--inspect` and `--inspect-brk` and how js-debugger works](https://github.com/microsoft/vscode-js-debug/blob/main/COMMON_PROBLEMS.md)

**Comment by polinasok** [comment]
The automation would be useful, but as there are low-overhead manual workarounds with attach and headless dlv available, it is unlikely that we will prioritize this over other more pressing work in a foreseeable future. I am going to close this with a MaybeLater label until we have more bandwidth or more user votes highlighting how critical this is.
