### ISSUE TITLE
debug golang If repeatedly click and cancel debug red point, an error will be reported, the program will jam

### ISSUE THREAD

**Issue by enjoycx** [golang/vscode-go#1544]
err info:
2021-06-05T02:58:39Z debug layer=debugger halting
Setting breakpoints during 'next', 'step in' or 'step out' halted delve and cancelled the next request2021-06-05T02:58:39Z info layer=debugger cleared breakpoint: []*api.Breakpoint{(*api.Breakpoint)(0xc00506e900)}

**Comment by suzmue** [comment]
Thanks for filing the issue! The error that you have included is intended to let the user know that setting a breakpoint while stepping halts the program, but does not resume it. This is intended behavior.

Are you able to hit continue/next/etc to resume the program after seeing this error?

**Comment by enjoycx** [comment]
it work when first time click and cancel not error  I can resume the program
info:
info layer=debugger created breakpoint: &api.Breakpoint{ID:1, Name:"", Addr:0x13645cb, Addrs:[]uint64{0x13645cb}, File:"payment.go", Line:106, FunctionName:"FPaymentCB", Cond:"", Tracepoint:false, TraceReturn:false, Goroutine:false, Stacktrace:0, Variables:[]string(nil), LoadArgs:(*api.LoadConfig)(0xc009064450), LoadLocals:(*api.LoadConfig)(0xc009064480), HitCount:map[string]uint64{}, TotalHitCount:0x0}
2021-06-09T06:09:49Z debug layer=debugger continuing
2021-06-09T06:09:54Z debug layer=debugger halting
2021-06-09T06:09:54Z info layer=debugger cleared breakpoint: []*api.Breakpoint{(*api.Breakpoint)(0xc0029a75c0)}
2021-06-09T06:09:54Z debug layer=debugger continuing

but there will be error  After a few times, will have to restart, which is a bit inconvenient

**Comment by polinasok** [comment]
@enjoycx
Is "debug red point" the red circle that appears when you set a breakpoint by clicking on the margins of your code?

From the partial log above without `"trace":"verbose"`, I am unable to tell what exact actions were performed and at what point things got "jammed" and how. That said, even if we get to the bottom of the issue, it is unlikely that we will be fixing it because you currently using the legacy debugger that is being replaced by the [new dlv-dap adapter](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md). I urge you to try your workflow with the new adapter and let us know if you are experiencing issues.

Just to make sure you know what to expect:
1. When setting a breakpoint during one of the "step" operations,
__Legacy__:  halts execution as if you clicked pause, sets breakpoint
__Dlv-dap__: halts execution as if you clicked pause, sets breakpoint
2.  When setting a breakpoint during "continue"
__Legacy__: halts execution, sets breakpoint, resumes execution (can be flaky due to concurrency issues)
__Dlv-dap__: halts execution as if you clicked pause, sets breakpoint

__Dlv-dap__ logs `debug layer=dap halting execution to set breakpoints` if extra logging is enabled.
Perhaps we should make this a visible info message in the Debug Console, so users are not surprised.

**Comment by hyangah** [comment]
@enjoycx Behavior around setting breakpoints or handling stop/continue had been changed a lot.
Please open a new issue if the problem persists or the new behavior (after updating `dlv-dap` to the latest version) does not meet your expectation. Thanks!
