### ISSUE TITLE
Can't specify go.formatFlags with language server

### ISSUE THREAD

**Issue by steeling** [golang/vscode-go#1552]
**Is your feature request related to a problem? Please describe.**
Yes, I'd like to satisfy golangci-lint, and still use the language server. This means I need to set the go.formatFlags = ["-local=github.com/my-org/my-repo"].

I can't do this and use the language server

**Describe the solution you'd like**
Allow go.formatFlags to work when useLanguageServer = true

**Describe alternatives you've considered**
?

**Comment by hyangah** [comment]
If your goal is to just set `-local` flag from `goimports`: https://github.com/golang/vscode-go/blob/master/docs/settings.md#formattinglocal

If your goal is to use a different formatter rather than using `gopls`'s formatting power: set the formatter with https://github.com/golang/vscode-go/blob/master/docs/settings.md#goformattool

**Comment by steeling** [comment]
thanks!
