### ISSUE TITLE
codespaces: add documentation for configuring Go

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#157]
See the discussion on https://github.com/microsoft/vscode-go/issues/2977, and specifically @hyangah's comment: https://github.com/microsoft/vscode-go/issues/2977#issuecomment-636092751.

**Comment by hyangah** [comment]
Many things had changed since then. online.visualstudio.com is moved to github codespaces, and vscode dev container team made significant progress wrt the container configuration. 

I just checked github codespaces, and no extra configuration was necessary for Go. 
The [GitHub codespaces documentation](https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/configuring-codespaces-for-your-project) still doesn't list Go, so I am not sure what's the current official status.

@Chuxel can I assume that GitHub codespaces supports Go environment?

**Comment by Chuxel** [comment]
@hyangah Yes, the default image now includes Go, Rust, and Ruby in addition to the platforms listed there.  People can also use the Go dev container if they prefer and we plan to add the same iteration process that exists for Remote - Containers into Codespaces (it's just a bit tricky to pull off).

**Comment by hyangah** [comment]
Thanks! @Chuxel 
I see Go is now listed in the repo [README.md](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/codespaces-linux). Sent https://github.com/github/docs/pull/2007 for [github docs](https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/configuring-codespaces-for-your-project) update.

I will close this issue.
