### ISSUE TITLE
debug: can't call method of struct and custom type

### ISSUE THREAD

**Issue by islishude** [golang/vscode-go#1580]
```go
package main

import "fmt"

type Tmp struct{}

func (Tmp) DoIt() {}

type Bytes32 [32]byte

func (Bytes32) Callit() {}

func main() {
	var t Tmp
	_ = t
	fmt.Println()

	var b Bytes32
	_ = b
	fmt.Println()
}
```

![image](https://user-images.githubusercontent.com/24730006/122632989-a8fc9080-d108-11eb-981c-6120a08a4f7d.png)

**Comment by hyangah** [comment]
That is because the go compiler removes unreferenced symbols (functions, methods, variables, ...) as part of compilation.
For example, try to call t.DoIt() or b.CallIt() somewhere in the scope).
I understand this is inconvenient but that's how this language works. 
![Screen Shot 2021-06-21 at 9 57 10 AM](https://user-images.githubusercontent.com/4999471/122774368-1dedd880-d277-11eb-84af-11bec7078a23.png)
