### ISSUE TITLE
VS Code version

### ISSUE THREAD

**Issue by diharter** [golang/vscode-go#1588]
The golang.go extension for VS code does not state the minimum version required for VS Cdoe.  When I tried to install from the installer on the extension page, it would fail to install, and give me the option to manually download.  Which I did.  When I tried to manually install the vsix file, I finally received the error message "Unable to install extension 'golang.go' as it is not compatible with VS Code '1.36.1'."  This requirement is important information upfront.

**Comment by hyangah** [comment]
@diharter Do you have any example of how/where other extensions present the required vscode version numbers?

The vscode engine info is embedded in the package.json file inside VSIX file (`engines` attribute). You can also lookup the package.json file by checking the package.json of the tagged version. As far as I know, newer versions of VS Code uses that info and automatically selects the suitable extension versions. If it failed to install, that's most likely, there is no version that would work with your vscode.

FYI the first version we released [requires 1.41 or newer.](https://github.com/golang/vscode-go/blob/v0.14.4/package.json#L76) and now we require 1.52 or newer.

**Comment by diharter** [comment]
I don't, but then again I haven't looked for it. This is the first
extension I've run into a problem installing with my version of vs code.
And just because no one else is doing it doesn't mean it's right.  Your
extension obviously didn't work on the version I had installed, and you
should state a minimum needed version.

**Comment by stamblerre** [comment]
> you should state a minimum needed version.

As @hyangah said, we do state a minimum version in the [`package.json`](https://github.com/golang/vscode-go/blob/39d70a64b472d7eef1bb1bd29f87e13844b8f8a8/package.json#L89) file.

> FYI the first version we released [requires 1.41 or newer.](https://github.com/golang/vscode-go/blob/v0.14.4/package.json#L76) and now we require 1.52 or newer.

This extension uses the language server protocol, so we typically require a fairly recent version of VS Code, since that protocol evolves quickly. As LSP becomes more popular, I expect other popular extensions will require recent versions of VS Code too.

@diharter: You may still be able to use this extension if you set `"go.useLanguageServer": false`, or if you install an older version of this extension (from 2020).

I don't think this case is common enough to justify adding a notice to the README, but perhaps we can add a line to the troubleshooting guide.
