### ISSUE TITLE
debug: launching dlv-dap doesn't honor backend attribute

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1591]
Like `--log`, dlv dap currently expects `--backend` to be specified via the command-line, not launch/attach configuration. But the extension maps `backend` in `launch.json` to `--backend` only for the legacy adapter, not dlv-dap. So any specification in launch.json (e.g. try erroneous "BLAH") will be ignored. 

We either need to update the extension or the dlv-dap code to parse the launch/attach configuration or both. Pro of doing this in the extension is that we will be ready for when we support the program specification at start-up. If we choose to accept this in dlv-dap code instead (and there is a pending rr PR exploring that option), how do we treat the global --backend flag (e.g. it might still be specified in external server mode manually on the command-line)? Does the launch/attach configuration override it if not empty?

**Comment by hyangah** [comment]
I think that belongs to the launch/attach param. The only reason that `--log` is not launch param is 1) due to the delve's limitation (how logging is structured) and 2) because we need logging before launch/attach requests are received. 

`backend` attribute is about how to set up a 'debugger' for a session, and Delve's `--backend` flag makes sense only when `dlv` headless server is used only for one kind of debugging (same program, build flag, ...). `dlv dap` command took a different approach and most of how to run debugging is determined through launch/attach parameters. IMO, `--backend` flag doesn't make sense for `dlv dap` - if `dlv dap` ever wants to support multi-use, long lived DAP server, I think this flag complicate things unnecessarily. Whether to ignore/warn/crash when the --backend flag is supplied is up to dlv dap implementation.

**Comment by polinasok** [comment]
I have verified that `"backend"` from `launch.json` is now acknowledged by dlv-dap.
