### ISSUE TITLE
Reading user input loops the program without debugging capability

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [golang/vscode-go#1718]
```
package main

import (
	"bufio"
	"fmt"
	"os"
)

func main() {
    reader := bufio.NewScanner(os.Stdin)

    for reader.Scan() {
        s := reader.Text()
        if s == "" {
            break
        }
        fmt.Println(s)
    }
}
```

debug console:
Starting: d:\Go\bin\dlv-dap.exe dap --listen=127.0.0.1:59530
DAP server listening at: 127.0.0.1:59530
123
Unable to process `evaluate`: debuggee is running
eee
Unable to process `evaluate`: debuggee is running
                  -- I press Enter only --
Unable to process `evaluate`: debuggee is running
                 -- stop execute by Shift-F5 --
Detaching and terminating target process
dlv dap (1060) exited with code: 0

Stop program only by Shift-F5.
Debug not working.

Golang, VSCode and go plugin latest version.
OS Win10 Pro

**Comment by polinasok** [comment]
Debug Console is not designed for entering stdin. It's not a terminal, where your process is foregrounded and can read stdin. It's a REPL environment for evaluating expressions, which is only possible when the target is not running (otherwise you get an error message).

Here is what you can do instead:
1. Run dlv server in a separate server terminal, where it will foreground your process, so you can enter stdin into that terminal.
```
$ ./dlv dap --listen=:54321
DAP server listening at: [::]:54321
debugserver-@(#)PROGRAM:LLDB  PROJECT:lldb-1205.0.27
 for x86_64.
Got a connection, launched process /Users/polina/delve/__debug_bin (pid = 8737).
123
read from stdin: 123

Exiting.
```
2. Use `launch.json` configuration to connect to this server.
```
{
            "name": "Launch via external dlv-dap",
            "type": "go",
            "request": "launch",
            "mode":"debug",
            "program": "${file}",
            "debugServer":54321, 
}
```

We know this is not ideal. Please see this issue for what else we are exploring in the long term: https://github.com/golang/vscode-go/issues/124#issuecomment-764447497.

**Comment by aleksandr-shevchenko** [comment]
Thanks!
