### ISSUE TITLE
debug: unable to create breakpoints

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#177]
See the original discussion on https://github.com/microsoft/vscode-go/issues/3025:

> ### What version of Go, VS Code & VS Code Go extension are you using?
> * Run `go version` to get version of Go
>   
>   * go version go1.13.6 darwin/amd64
> * Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
>   
>   * Version: 1.41.1
> * Check your installed extensions to get the version of the VS Code Go extension
>   
>   * 0.12.0
> * Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
>   
>   * darwin amd64
> 
> ### Describe the bug
> All breakpoints I set are unverified. When I use dlv in the command line, I can set breakpoints without any problems using a relative path or using the full path.
> 
> This is the error I see when I try to set breakpoints in vscode:
> 
> ```
> Error on CreateBreakpoint: could not find statement at <path/to/line>, please use a line with a statement
> ```
> 
> This is the create breakpoints request:
> 
> ```
> From client: setBreakpoints({"source":{"name":"main.go","path":"/full/path/to/main.go"},"lines":[6],"breakpoints":[{"line":6}],"sourceModified":false})
> ```
> 
> This is the response:
> 
> ```
> Creating on: /full/path/to/main.go:6
> Error on CreateBreakpoint: could not find statement at /full/path/to/main.go:6, please use a line with a statement
> All set:[null]
> To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":6}]}}
> SetBreakPointsResponse
> From client: setExceptionBreakpoints({"filters":[]})
> To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
> From client: configurationDone(undefined)
> ```
> 
> I get that error regardless of which line I set the breakpoint on.

This seems like a legitimate error that will be difficult to reproduce. We should probably add some more logging to understand what's going on.

/cc @quoctruong @hyangah

**Comment by stamblerre** [comment]
@austintackaberry can you share your VS Code settings (Ctrl+Shift+P -> Preferences: Open Settings (JSON))? I recently noticed [this common issue](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#unverified-breakpoint-or-variables-not-loading-when-debugging-a-binary), which suggests making sure that you are not building the binary with optimizations. Is it possible that you have added flags in your settings that might be affecting this?

**Comment by austintackaberry** [comment]
I don't think that the issue is related to build flags because it works as expected when using delve CLI, and I am building the executable the same way when I use the delve CLI.

To be clear, I am building the binary outside of VSCode, in the terminal. And then trying to run the executable with the debugger.

**Comment by hyangah** [comment]
Thanks @austintackaberry for sharing the settings.json and launch.json files - I don't see anything unusual and I could successfully debug a trivial binary with those settings files. :-( So, problems may be somewhere that's not specified in those settings. Have you encountered the same issue when using a mode other than `exec`? (e.g. `debug` or `auto`)? 

Is there anyone who can reproduce this issue with an open source project (preferably reproducible on mac or linux, since windows may have other issues)? I will need 

  - the repository that I can clone, and where exactly you tried to set the breakpoint (filename/line number)
  - the exact build command to build the executable
  - launch.json/settings.json 
  - dlv version should be up-to-date

Thank you for your patience!

**Comment by austintackaberry** [comment]
I am able to successfully add and stop on breakpoints when clicking `debug test` button above individual test functions. Thank you for taking the time to help me figure out this issue, but I don't know if I will have time to reproduce on open source project. Given that, I understand if you want to close this issue. Thanks again!

**Comment by stamblerre** [comment]
Thanks for the update - glad things are working! I'll close this issue, but feel free to reopen or file a new issue if you're interested in pursuing it further.

**Comment by grantcurell** [comment]
I'm not doing anything in WSL or a container - just a folder on Windows and am seeing the same problem. Did anyone find a concrete resolution to this?

**Comment by rosakolejarz** [comment]
> I am able to successfully add and stop on breakpoints when clicking `debug test` button above individual test functions. Thank you for taking the time to help me figure out this issue, but I don't know if I will have time to reproduce on open source project. Given that, I understand if you want to close this issue. Thanks again!

I had the same problem and it turned out that all works fine when I changed path from relative to full in the invoking command. 
Unfortunately all the logs in both scenarios are the same until the line with:
`Error on CreateBreakpoint: could not find statement at /.../.../main.go:13, please use a line with a statement`
I discovered the solution by accident, having given up earlier...

not working:
`dlv exec --continue --accept-multiclient --headless --listen=:56268 --api-version=2 --log binary`

working: 
`dlv exec --continue --accept-multiclient --headless --listen=:56268 --api-version=2 --log /full/path/to/binary`
