### ISSUE TITLE
Extension causes high cpu load - during loading

### ISSUE THREAD

**Issue by brunopiaui** [golang/vscode-go#178]
- Issue Type: `Performance`
- Extension Name: `go-nightly`
- Extension Version: `2020.6.322`
- OS Version: `Linux x64 5.3.0-56-generic`
- VSCode version: `1.46.0-insider`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[golang.go-nightly-unresponsive.cpuprofile.txt](https://github.com/golang/vscode-go/files/4741624/golang.go-nightly-unresponsive.cpuprofile.txt)

**Comment by hyangah** [comment]
@brunopiaui thanks for the report. I guess the profile was taken during the extension load time. The profile shows most time was spent reading required modules. I hope bundling (#53) and reducing dependencies can lower the overhead.

![Screen Shot 2020-06-07 at 10 10 54 PM](https://user-images.githubusercontent.com/4999471/83986738-df0b1000-a90b-11ea-8076-a614a85ac676.png)

**Comment by hyangah** [comment]
@OneOfOne recently changed to bundle the extension (golang/vscode-go#53) - which means instead of reading in a couple of thousands of js files during initialization, now we need to read one js file. I see initialization time down from multiple hundreds ms to under a hundred ms on my machine. I am not sure if this will help in your case, but definitely worth giving a try. The pre-release version is released as golang.go-nightly. (https://marketplace.visualstudio.com/items?itemName=golang.go-nightly)  To use this you will need disable or uninstall the golang.go extension though.

Let us know if it helps. Thanks!

**Comment by leroypa** [comment]
Same problem for me running Terminal within VSCode and Go Run

**Comment by stamblerre** [comment]
Closing, as this issue is outdated and the bundled extension has been available for quite some time.
