### ISSUE TITLE
Syntax highlighting for Go 1.13 number literals

### ISSUE THREAD

**Issue by olivierlemasle** [golang/vscode-go#180]
**Is your feature request related to a problem? Please describe.**

Since version 1.13, [Go supports digit separators, binary and octal number literals, etc.](https://golang.org/doc/go1.13#language). These changes came from [this accepted proposal](https://github.com/golang/proposal/blob/master/design/19308-number-literals.md).

However, `vscode-go` do not display these numbers like the other numbers:

![image](https://user-images.githubusercontent.com/628140/83969911-f083f600-a8d2-11ea-8b69-dd0b68ac167a.png)

**Describe the solution you'd like**

In the screenshot above, the 4 numbers are identical (same value 10000); they should be displayed in the same color.

**Comment by stamblerre** [comment]
Thanks for the report!

Syntax highlighting for Go in VS Code is provided by https://github.com/jeff-hykin/better-go-syntax, not this extension. Looks like the issue you reported is https://github.com/jeff-hykin/better-go-syntax/issues/3. I'll go ahead and close this issue here, but we'll work on contributing a fix to that repository.
