### ISSUE TITLE
Add toggle for deemphasized code

### ISSUE THREAD

**Issue by ansiwen** [golang/vscode-go#1916]
**Is your feature request related to a problem? Please describe.**
Since go-delve/delve#2522 stack frames in runtime have the "deemphasize" presentation hint. This results in vscode to always jump out of the runtime stack frames while stepping through runtime code. Especially when debugging runtime changes this is not usable and requires to switch back to the legacy debug adapter.

**Describe the solution you'd like**
There needs to be a possibility to ignore the presentation hint globally, or to toggle it per debugging session/frame by right clicking on the stack frame and toggle it similar to [Toggle skipping this file](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code). Alternatively, similar to these skipping rules, setting a breakpoint in runtime code could/should disable the deemphasizing.

**Comment by hyangah** [comment]
@suzmue @polinasok 
Related: should this functionality be somehow combined with the new `HideSystemGoroutines` feature?

**Comment by suzmue** [comment]
@ansiwen Thanks for the feedback.

After seeing this feature in use for a while, I think we should consider removing the source presentation hint all together. It would still be possible to provide a visual indication of runtime vs source stack frames, without deemphasizing the source.

This is what it currently looks like (`source.presentationHint="deemphasize"`):
<img width="919" alt="Screen Shot 2021-11-29 at 11 11 30 AM" src="https://user-images.githubusercontent.com/6634754/143902790-20006bbb-931c-41c2-987d-10ab1e4bb914.png">

If we move the presentation hint 'subtle' to the stack frame instead of the source, we can instead have the following (`presentationHint="subtle"`):
<img width="925" alt="Screen Shot 2021-11-29 at 11 10 55 AM" src="https://user-images.githubusercontent.com/6634754/143902685-f06c8c19-96da-4274-b7f1-9e6b02d15e72.png">
>

**Comment by polinasok** [comment]
I think using `subtle` to visible differentiate user and runtime frames is a good idea.. We could also collapse only the frames at the bottom of the stack.

Is there such thing as too many configurable launch options? It is does seem more intuitive for the user if these things were evaluated on the fly dynamically - i.e. sticky expansions. It would have been good to combine hiding system frames and goroutines into one option. Too late now? We have released it already, haven't we?

**Comment by polinasok** [comment]
We had a discussion offline and all are in agreement that we don't need to collapsing can be removed in favor of `subtle`.
The option to hide goroutines has not been released beyond Nightly. We could nest it under some kind of visibility config like `viewConfig`, so all options to hide/show things in the UI are grouped together. But that's beyond the scope of this issue.

**Comment by hyangah** [comment]
@ansiwen go-delve/delve#2810 was merged and available from the head. Please update `dlv-dap` ("Go: Install/Update Tools"). Thanks!
