### ISSUE TITLE
How do I set up not to automatically format a particular file in vscode

### ISSUE THREAD

**Issue by remainfox** [golang/vscode-go#1963]
**How do I set up not to automatically format a particular file in vscode**

When I save a `go file`, I `don't` want vscode to format the file automatically

How do I set up vscode to `just not automate formatting certain files` , thanks

**Comment by butuzov** [comment]
It's tricky and you should not want it, imo. but you can achieve it in next ways:

- Manually save such files with the command "File: Save without Formatting" (`⌘+K  S`)
- Automatically disable this file association with go language.
    ```jsonc
   "[go]": {
        "editor.formatOnSave": true,
    },
    "files.associations": {
        "queue_test.go": "plaintext"
    }
    ```

**Comment by hyangah** [comment]
In addition to what @butuzov said (thanks!!) you can also disable the formatting completely (not only for a particular file).
```
"[go]": { "editor.formatOnSave": false }
```

But that is not encouraged.

If you don't want auto-formatting because the file was auto-generated, mark clearly that the file was generated by adding a comment that matches `^// Code generated .* DO NOT EDIT\.$` (https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source)
