### ISSUE TITLE
Struct Tag Syntax Highlighting

### ISSUE THREAD

**Issue by vidhanio** [golang/vscode-go#1984]
**Describe the solution you'd like**
A useful feature would be to have the `json:` part of the struct Tag be a different color from the actual name. This would help readability of the code and help make sure the syntax being used is correct.

**Comment by hyangah** [comment]
There are currently two paths to implement this.
1) improve TextMate syntax used by VS Code (send a contribution or FR to https://github.com/jeff-hykin/better-go-syntax) and ask VS Code to update their vendored copy. This is not in the scope of this extension. 
2) implement this in gopls's semantic token. We will discuss with gopls devs.

Not sure about helping correct usage of the syntax. I think that would be more explicit - e.g. diagnostics. (cc @pjweinb @findleyr )

**Comment by pjweinb** [comment]
The Go language allows any string as a tag. The reflect package supports a convention: "tag strings are a concatenation of optionally space-separated key:"value" pairs. Each key is a non-empty string consisting of non-control characters other than space (U+0020 ' '), quote (U+0022 '"'), and colon (U+003A ':'). Each value is quoted using U+0022 '"' characters and Go string literal syntax." There are maybe some unused semantic tokens, if it's decided to implement this that way. If it were to be done as a diagnostic, perhaps a non-conventional tag should be Warning, rather than Error.

**Comment by vidhanio** [comment]
This is already in the vscode extension through `structtag`, unless I am missing something in your comment.

![image](https://user-images.githubusercontent.com/41439633/148099768-c5d62c4e-ec3d-4986-912d-f934299b532f.png)

**Comment by hyangah** [comment]
@vidhanio I was questioning the utility of the syntax highlighting as a mean to surface usage errors. Diagnostics which vscode presents with squiggles should provide enough visual hint already, shouldn't it?

**Comment by vidhanio** [comment]
Yes, I guess that does invalidate that part of my issue 😅, I forgot about that, sorry!
