### ISSUE TITLE
Search for implementations feature

### ISSUE THREAD

**Issue by sonalys** [golang/vscode-go#2074]
**Is your feature request related to a problem? Please describe.**
Yes, I'm frustrated that whenever I'm searching for an interface implementation, it will always show the mock implementation first, thus polluting the search, because I will never want to see the automatic generated mock implementation for that interface.

**Describe the solution you'd like**
I would love that we could configure the extension so it would ignore the specified folders whenever looking for implementations.

**Describe alternatives you've considered**
I don't know any other alternatives.

**Additional context**
![image](https://user-images.githubusercontent.com/15274059/154910613-fabb68af-6ce8-4847-9a62-776d254cec92.png)

**Comment by hyangah** [comment]
Can you elaborate a bit more about "polluting the search"? 

The implementations result page always organizes the findings based on the file URIs. Unless you explicitly expand the files from the `mocks` package, that will take a single line in the result. Or, do you mean that since you have so many mock implementations of an interface that the search window is filled with entries for the mocks?

If you want to configure the extension, do you want it to be applied only to the implementations search? If not, isn't gopls `directoryFilter` setting sufficient for you? That will exclude all the analysis and intellisense on the listed directories. 

I wish VS Code supported filtering option from this REFERENCES: IMPLEMENTATIONS panel, but I am not sure if that satisfies your needs.

**Comment by sonalys** [comment]
Hello @hyangah, sure, I can ellaborate more.
There are shortcuts for going straight to the implementation, however when there are more than 1 implementation for that interface, it will open a popup instead and you have to select one of the implementations to jump into.
The recommended implementation is always the mock one, maybe because of the URI as you said.

I didn't knew about this directoryFilter, I tried it and it still dont work with implementation finding.

I tried creating an issue for filtering references in the vscode repository, but, because I mentioned go in the issue, they thought it would be a vscode-go issue. I don't know about the underlying logic of the IDE and the go extension.

**Comment by findleyr** [comment]
I don't think this is appropriate for directoryFilter, because presumably the mock folders are necessary for testing, and therefore should be included in the workspace.

Can you share more about the mocks? How are they generated, and how might they be identified?

I don't think we should add a setting here, as we can't expect users to find that setting for this minor annoyance. Most likely they would just live with it. We should either fix it for all users, or do nothing.

Assuming that the mocks follow the convention of go.dev/issues/13560, i.e. have a `DO NOT EDIT` header, we could simply down-rank results that are in generated files. That seems like an unambigious rule that would work in most cases.

**Comment by sonalys** [comment]
> I don't think this is appropriate for directoryFilter, because presumably the mock folders are necessary for testing, and therefore should be included in the workspace.
> 
> Can you share more about the mocks? How are they generated, and how might they be identified?
> 
> I don't think we should add a setting here, as we can't expect users to find that setting for this minor annoyance. Most likely they would just live with it. We should either fix it for all users, or do nothing.
> 
> Assuming that the mocks follow the convention of go.dev/issues/13560, i.e. have a `DO NOT EDIT` header, we could simply down-rank results that are in generated files. That seems like an unambigious rule that would work in most cases.

I would love that
