### ISSUE TITLE
contributing: add `npm run lint` hook before `git codereview change`

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#208]
It would be nice if we could have a lint hook that runs before you mail your change, similar to `git codereview gofmt`.

**Comment by hyangah** [comment]
Or we can consider [husky](https://www.npmjs.com/package/husky) or other similar npm modules. 

https://codeburst.io/continuous-integration-lint-staged-husky-pre-commit-hook-test-setup-47f8172924fc

**Comment by hyangah** [comment]
Discussed in a node.js community and they are not fond of the idea of utilizing the precommit hook (because it executes a program by default and adds dependencies). Instead, their recommendation is to incorporate `npm run lint` to `npm run test` script - we need some light weight smoke test and ask users to run always)

Also recommend users to configure their editors to run lint on save, etc. 

And, we can change our CI not to stop due to the lint error. 

What do you think? @stamblerre @polinasok

**Comment by stamblerre** [comment]
That all sounds good to me. Maybe CI could test before linting so that test failures get looked at first, but lint still blocks CI?

**Comment by polinasok** [comment]
If lint errors are a blocker, it makes sense to test automatically and highlight/block instead of just relying on people to configure their editors. However a reminder to run lint before you uploaded a PR and spammed everybody with your easily preventable failure would be helpful too. Having it in the contributing docs is helpful, but over time people stop to look there. Having a quick checklist as part of the default commit message that needs to be read and cleaned up is a more sure way that this does not get overlooked.

**Comment by hyangah** [comment]
The lint error does not block other tests any more. So, closing.
