### ISSUE TITLE
docs: move files in `docs` to Wiki

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2094]
### Background

In https://github.com/microsoft/vscode-go/pull/3168 we moved all the contents from Wiki to the `docs` directory.

The rationals behind the move were 
  * GitHub Wiki repo is separate from the regular github repo and does not allow convenient ways of reviewing PRs and inspecting changes. (https://github.com/microsoft/vscode-go/issues/3148).
  * We don't want to allow Wiki contents to be editable without proper review process. GitHub restricts search engines' crawling of Wiki contents if the edit permission is not restricted. https://github.com/github/feedback/discussions/4992 And we've seen Wikis without proper review process often suffering from vandalism or inaccuracy.  
  * Users without edit permissions cannot easily contribute to the Wiki contents, like other markdown files in the repo using GitHub's Markdown edit/preview feature. So, bar for contribution is high.
  
With the move, however, we had to give up GitHub's Wiki UI that allows more customization & search &
index options suitable for documentations. Documentation inside the main project repo is not easily
searchable either.

### Proposal

Follow the github.com/microsoft/vscode project's wiki page setup. (https://github.com/microsoft/vscode/wiki vs https://github.com/Microsoft/vscode-wiki)

* Maintain the canonical version of wiki pages in `vscode-go` repo's `docs` directory.
   * All updates must go through the proper review process.
   * Users can update contents from github's UI and PR workflows.
   * Document autogeneration scripts will continue to work.
* GitHub Action workflow will copy the data in `docs` directory to `github.com/golang/vscode-go.wiki` repo.
* Access to github.com/golang/vscode-go/wiki.git is restricted so search engines can crawl them.

### Note

1. We may want to move some of user-facing settings/features/tutorials to more publicly visible webpage. Even after then, wiki will continue to serve as a place to host
  * internal documentation for project management (triage process, release process, project milestone, contribution guide, etc)
  * less polished, transient tips & tricks
  * compatibility info
  * links to proposals or design docs
  
  cc @golang/tools-team 

EDIT: (2022-04-17) Originally I proposed to have a separate repo to host documentation. But that complicates automated documentation generation with which we wanted to maintain consistency between the current code & the settings. Keeping two separate repositories isn't ideal either. Instead, I changed this proposal to use `docs` directory as the place we keep all the wiki page contents, and mirror the contents to the wiki page.

**Comment by nelsonjchen** [comment]
May I make a suggestion? It might be a good idea to make the generated markdown for the Wikis include a custom "Edit on GitHub" link that auto-forks/opens the source markdown for editing. 

As an example of another organization's approach to the wiki issue, see https://libgdx.com/wiki/ and search for "Edit on GitHub" on that page for an example. It should be possible to have that as the "Edit on GitHub" link in the markdown that's pushed to the GitHub Wiki instead of the generic and non-specific "send a pull request" in the footer. 

---

I run https://github-wiki-see.page so I'm very aware of the challenges that organizations and individuals have in trying to get their GitHub Wiki content officially indexable. Please let me know if you have any questions.

**Comment by 1989shack** [comment]
Integrated platforms across the internet, Domains Registrar, Domains WHOIS Records, Servers Hosting Platform databases system Admin flow
