### ISSUE TITLE
Be able to run tests with another command

### ISSUE THREAD

**Issue by MarcelXia** [golang/vscode-go#2266]
There's a lot configurable, like "go.formatTool": "goimports".
If there was something equal to run test with , for example 	"go.testTool": "gotest",
then people like me would have the benefit of running the tool they're used to run outside VSC.

I think, this go test command is hard coded, so for me there's no solution for it.

**Comment by hyangah** [comment]
I don't know exactly what you want to do but in many cases, 
users use `"go.alternateTools": { "go": "<path to your custom go>" }`
But the replaced `go` should be named as 'go' - because tools (that this extension uses) use hard coded 'go'.

Or if you want more complicated ones, tasks.json is another way to configure:
https://github.com/golang/vscode-go/wiki/tasks

**Comment by MarcelXia** [comment]
I described exactly what I wanted. 
We can choose all kinds of tools for stuff,  but when it comes to running tests, we can't.
See my example, it's pretty clear. and if you don't understand, please ask more info instead of closing an issue.

**Comment by hyangah** [comment]
@MarcelXia I already offered the solution in my previous comment. `"go.alternateTools"` is a newer flag and provides all the flexibility. If you want more than that, I am afraid that's beyond the scope of this extension project.

**Comment by hyangah** [comment]
Yes, you can run `gotest` using tasks.json configuration.

AFAIK "gotest" is a "go test" with color. The extension cares only about the `-json` mode go test output to process the output programatically and the use of ansi color makes processing the output harder.
