### ISSUE TITLE
x/tools: Tools install/update error in vscode

### ISSUE THREAD

**Issue by shenguanjiejie** [golang/vscode-go#2279]
Golang: 1.18.3
vscode: Version: 1.67.2 (Universal)
![image](https://user-images.githubusercontent.com/9425605/172154461-5ba889d5-c3af-4983-bb3e-82eb1a2d267d.png)
![image](https://user-images.githubusercontent.com/9425605/172154489-4777d834-4fa3-4d7c-b80c-0baacc57fa6b.png)

I had try solute it with 
1. reinstall vscode 
2. uninstall all vscode plugins and reinstall go plugin
3. reinstall go
not work either.

╰ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rj/Library/Caches/go-build"
GOENV="/Users/rj/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rj/go/pkg/mod"
GONOPROXY="*.sensetime.com"
GONOSUMDB="*.sensetime.com"
GOOS="darwin"
GOPATH="/Users/rj/go"
GOPRIVATE="*.sensetime.com"
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bm/5666f1890t7g1w4165p97kgr0000gn/T/go-build114183488=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by hyangah** [comment]
It looks like you have a corrupted version of extension installed (1) or the extension failed to get activated properly due to errors (2) 

To exclude the case (1): uninstall the extension AND delete the directory under `$HOME/.vscode/extensions/golang.go-*` AND restart&reinstall the go extension.

If it doesn't fix the issue, can you collect the information for debugging the case (2)?

* Make sure the workspace is "Trusted", no error prompt or notification appeared, and the Go version status bar item ("Go 1.18.3") appears at the bottom of the window 
* "Developer: Toggle Developer Tools" -> Console tab, see if there is any error message. 
* "View: Toggle Output" -> See "Log (Extension Host)" to see if there is any error.

**Comment by shenguanjiejie** [comment]
@hyangah  I had uninstall vscode, removed "$HOME/.vscode/extensions" and "~/Library/Application Support/Code" folder, then install vscode. only 'go' a single extension. 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/9425605/172281914-c1583550-4faf-44c3-8b0f-f08769fe0e47.png">
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/9425605/172282489-30a5e7d5-e771-4a5a-9553-41665bbb378a.png">
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/9425605/172283836-49262fdb-ca98-44e2-bbfc-1e5f8e1227df.png">

**Comment by shenguanjiejie** [comment]
My colleague has the same problem as me.

**Comment by shenguanjiejie** [comment]
I had tried to install the 0.31 or 0.32 version of the go extension. doesn't work.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/9425605/172292556-54795428-a4f8-46c5-9fe3-91f61104229b.png">

**Comment by shenguanjiejie** [comment]
Look like there have some limits in my company, I have resolved them now.
