### ISSUE TITLE
The window has crashed, reason: 'crashed', code: '-1073741819' on Windows

### ISSUE THREAD

**Issue by yuandongx** [golang/vscode-go#2280]
```
[Extension Host] Server: {
  "Commands": [
    "gopls.add_dependency",
    "gopls.add_import",
    "gopls.apply_fix",
    "gopls.check_upgrades",
    "gopls.edit_go_directive",
    "gopls.gc_details",
    "gopls.generate",
    "gopls.generate_gopls_mod",
    "gopls.go_get_package",
    "gopls.list_imports",
    "gopls.list_known_packages",
    "gopls.regenerate_cgo",
    "gopls.remove_dependency",
    "gopls.run_tests",
    "gopls.run_vulncheck_exp",
    "gopls.start_debugging",
    "gopls.test",
    "gopls.tidy",
    "gopls.toggle_gc_details",
    "gopls.update_go_sum",
    "gopls.upgrade_dependency",
    "gopls.vendor"
  ],
  "Name": "gopls",
  "Version": "v0.8.4",
  "GoVersion": "go1.18.3"
}```

### Describe the bug

 ERR no identifier found: Error: no identifier found
	at handleResponse (c:\Users\xuyuandong\.vscode\extensions\golang.go-0.33.1\dist\goMain.js:4366:40)
	at processMessageQueue (c:\Users\xuyuandong\.vscode\extensions\golang.go-0.33.1\dist\goMain.js:4204:13)
	at Immediate.<anonymous> (c:\Users\xuyuandong\.vscode\extensions\golang.go-0.33.1\dist\goMain.js:4190:11)
	at processImmediate (node:internal/timers:464:21)

### Screenshots or recordings
![3d9bcb37105ede1102f8a097818dde7](https://user-images.githubusercontent.com/35824522/172358877-fe659ef5-129c-4502-830c-ce5984a38b0d.png)

**Comment by yuandongx** [comment]
![3d9bcb37105ede1102f8a097818dde7](https://user-images.githubusercontent.com/35824522/172359674-53219e64-f258-46b6-841e-6ffffd960cd2.png)

**Comment by hyangah** [comment]
@yuandongx Is there anything unique in your dev environment? 

The extension and its language server invokes command line tools (including `go.exe` as subprocesses). Historically, we've seen this type of crashes caused by package manager, security/firewall, uncommon go command customization, etc. 

For example,  
* https://github.com/golang/vscode-go/issues/2229 (a bug in [aqua](https://github.com/aquaproj/aqua/issues/710) crashed the vscode window)
* https://github.com/golang/vscode-go/issues/2279 (enterprise-specific security restriction interfered normal command 
 line execution and crashed the extension host)


The trace (`no identifier found`, from LSP json rpc response handling logic) looks like more of a symptom rather than the cause of the crash.
