### ISSUE TITLE
Clicking "run test" fails with clang not found yet it's in the path and works

### ISSUE THREAD

**Issue by Southclaws** [golang/vscode-go#2284]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary></summary><be>

```
❯ go version
go version go1.18.3 darwin/amd64

❯ gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.11-0.20220513164230-dfee1649af67 h1:CJwk4qG1fov4WP7/DWhhb7OQVZlQKAl1rEMnDF+ceGU=
    golang.org/x/vuln@v0.0.0-20220503210553-a5481fb0c8be h1:jokAF1mfylAi1iTQx7C44B7vyXUcSEMw8eDv0PzNu8s=
    honnef.co/go/tools@v0.3.0 h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18

❯ code -v
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
arm64

Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/southclaws/go
GOROOT: /usr/local/go
PATH: /Users/southclaws/Library/Caches/fnm_multishells/29771_1654708553310/bin:/Users/southclaws/flutter/bin:/Users/southclaws/.poetry/bin:/Users/southclaws/.cargo/bin:/Users/southclaws/.local/bin:/Users/southclaws/bin:/Users/southclaws/go/bin:/usr/local/go/bin:/opt/homebrew/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

	go:	/usr/local/go/bin/go: go version go1.18.3 darwin/amd64

	gotests:	/Users/southclaws/go/bin/gotests	(version: v1.6.0 built with go: go1.18)
	gomodifytags:	/Users/southclaws/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18)
	impl:	/Users/southclaws/go/bin/impl	(version: v1.1.0 built with go: go1.18)
	goplay:	/Users/southclaws/go/bin/goplay	(version: v1.0.0 built with go: go1.18)
	golangci-lint:	/Users/southclaws/go/bin/golangci-lint	(version: v1.46.2 built with go: go1.18)
	gopls:	/Users/southclaws/go/bin/gopls	(version: v0.8.4 built with go: go1.18)

go env
Workspace Folder (odin): /Users/southclaws/Work/odin/odin
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/southclaws/Library/Caches/go-build"
	GOENV="/Users/southclaws/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/southclaws/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/southclaws/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.18.3"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/southclaws/Work/odin/odin/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/86/sjnhclhd7_s9kpgn2_r9b13c0000gn/T/go-build2427442603=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Share the Go related settings you have added/edited

```
"go.vetOnSave": "off",
"go.formatTool": "goformat",
"go.toolsManagement.autoUpdate": true,
"go.alternateTools": {
    "goformat": "gofumpt"
  }
"go.coverageDecorator": {
    "coveredGutterStyle": "blockblue",
    "uncoveredGutterStyle": "slashyellow",
    "uncoveredHighlightColor": "hsla(0, 70%, 44%, 0.5)",
    "type": "highlight",
    "uncoveredBorderColor": "red",
    "coveredHighlightColor": "hsla(136, 70%, 35%, 0.5)"
  }
"go.lintOnSave": "workspace",
"go.buildOnSave": "off",
"go.lintFlags": ["--timeout=5m"],
"go.languageServerExperimentalFeatures": {
    "format": false
  }
"go.testFlags": ["-v", "-race"],
"go.lintTool": "golangci-lint",
"go.testEnvVars": {
    "PATH": "${env:PATH}:/opt/homebrew/bin"
  }
```

### Describe the bug

It appears that the environment isn't being propagated to the "Run tests" feature. I've opened vscode from the terminal and the .app file and never had any issues until this week. vscode was updated that was the only change.

Basically, when hitting the "run test" button in the source code view, the tests won't build due to not being able to find clang.

![image](https://user-images.githubusercontent.com/1636971/172826556-fb21f5da-f022-4663-a404-7f5813556449.png)

(Not sure what this thing is called)

clang is available and is being picked up by the terminal. It's in my path environment variable as it's pretty much a default install on mac afaik.

If I click "Debug test" it runs fine, and surely the debugger would also require clang to actually compile the code which includes some cgo in the dependency tree.

So it appears that "Run test" isn't finding clang but "Debug test" is.

For now I can run tests using the debugger, only downside is it takes a lot longer to compile and run.

### Steps to reproduce the behavior:

Open vscode from terminal or .app/spotlight

Hit "Run tests" in a cgo project on a macbook.

### Screenshots or recordings

https://user-images.githubusercontent.com/1636971/172827883-d91429a7-159e-4dbd-9b67-6c2f0f3a5228.mov

**Comment by hyangah** [comment]
@Southclaws do you see the same if you don't use the vscode variables like `${env:PATH}` in the settings?

```
"go.testEnvVars": {
    "PATH": "${env:PATH}:/opt/homebrew/bin"
}
```

VSCode does not resolve variables in settings (https://github.com/microsoft/vscode/issues/2809). They are resolved only when used in Tasks or Debug configuration. So currently it's up to the extension to resolve variables appearing in settings. We've done some ad-hoc variable resolution for frequently used variables ([example](https://github.com/golang/vscode-go/blob/ff8fb94d7f365fafb1088fb195c119e6abac1a00/src/util.ts#L440)), but not all variables syntaxes are supported.

So, by having this setting, the extension ended up running "go test" with `PATH=\${env:PATH}:/opt/homebrew/bin` env var. 
([code](https://github.com/golang/vscode-go/blob/cdd8871cc20b725c1783fb512b750bb96ba08dc7/src/testUtils.ts#L309-L310))

**Why did it work in the debug mode, then?**

The debugging is implemented by populating an appropriate debug configuration and asking vscode to start a debug session with the debug configuration. ([code](https://github.com/golang/vscode-go/blob/8bc0703b44357592184a18364de5fcae51368156/src/goTest.ts#L260-L274). VSCode's debug API translates and resolves variables internally. So, `${env:PATH}` is resolved correctly as described in https://code.visualstudio.com/docs/editor/variables-reference. 

**Workarounds:**
Avoid use of variables in settings.json. :-(

**What should we do** - here are some options I am thinking. Let us know if there are easier ways.

Option 1: we implement our own custom variables resolve logic. We will never fully match vscode's.

Option 2: I heard there is a third-party npm package that does that but there is no guarantee that it behaves like vscode's variable resolution.

Option 3: utilize [custom execution](https://code.visualstudio.com/api/extension-guides/task-provider#customexecution) api when running tests, instead of depending on node.js child_process directly. Then the task API will handle variable resolutions. Our extension also needs to process the test outputs - e.g. process `go test -json` output, translate file paths/test success/failure results, and reflect the results to test explorer, etc, so we need some pseudoterminal implementation.

Option 4: do nothing, and wait until vscode team finally offers an api for variables resolution.

**Comment by Southclaws** [comment]
Ah thanks, that fixed it.

This outcome was unexpected though, as that's been in my config for a long time - it was added to resolve another problem I had. I think that problem was that some of my tests for https://github.com/Southclaws/supervillain/ need to execute `yarn` to compile generated TypeScript code and this wasn't working until I added this entry to my config.

That's a problem to solve separately though, for now this is fixed, thanks again!
