### ISSUE TITLE
debug: use Delve's DAP implementation

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#23]
Delve supports debug adapter protocol natively (`dlv dap`).
https://github.com/go-delve/delve/tree/master/service/dap

Implement the debug feature using it and deprecate the dlv wrapper (`src/debug/goDebug.ts`). 

@polinasok @quoctruong @ramya-rao-a

**Comment by polinasok** [comment]
DAP-in-delve work is tracked under https://github.com/go-delve/delve/issues/1515
You can reference [server.go::handleRequest()](https://github.com/go-delve/delve/blob/4a9b3419d13abcc850acf80770f5103191d06a1f/service/dap/server.go#L183) for an account of which requests are already supported and which ones are still TODO.

**Comment by lggomez** [comment]
I would like to add that some of the current issues due to incompatibility between the current DAP and delve that should be solved (at least partially) are the following: #118 #119 #129 #130

Tacking these would help a lot to the goal of achieving a seamless debug experience

**Comment by polinasok** [comment]
### Before
```
VSCODE <=dap=> ADAPTER <=json-rpc=> DELVE
```
* The [current adaptor](https://github.com/golang/vscode-go/tree/master/src/debugAdapter) acts as an intermediary between vscode and delve.
* It is registered as an adapter in [package.json](https://github.com/golang/vscode-go/blob/master/package.json) under `debuggers` for [type "go"](https://github.com/golang/vscode-go/blob/6ca980efe641b25e4b5f2b4cbade7d6e8eea9426/package.json#L357).
* It is launched by the extension as a separate Node.js process at the beginning of each debug session.
* It communicates with the editor using DAP over stdin/stdout and with delve over JSON-RPC.
* It hands initialize and shutdown sequences for the debug session.
* In response to `launch` or `attach` request, it launches delve, which in turn builds, executes or attaches to the debugee) or connects to an already running server.

### After
```
VSCODE <=dap=> DELVE
```
* [Delve with DAP](https://github.com/go-delve/delve/blob/master/service/dap/server.go) will act as an adaptor and debugger in one without the middleman.
* It will be registered in [package.json](https://github.com/golang/vscode-go/blob/master/package.json) under a new `debuggers` type, so we can support both adaptors during the transition period.
* It will be launched by the extension as a separate server process with `dlv dap` command at the beginning of each debug session. (To be revisited if dlv-dap starts supporting more than one debug session.) This can be done similarly to how the `dlv` command is [spawned](https://github.com/microsoft/vscode-go/blob/fc95cc5110cecbb977d96ad416df680a90e7438c/src/debugAdapter/goDebug.ts#L552) in the existing adaptor. 
* It will communicate with the editor using DAP over TCP connection.
* It will handle the initialize and shutdown sequences for the debug session.
* In response to `launch` or `attach` request, it will build, test, execute or attach to the debuggee  or connect to a remote server.

**Comment by polinasok** [comment]
I updated the [overview comment](https://github.com/golang/vscode-go/issues/23#issuecomment-641906002) to include the 2nd option with the thin adapter, so we have both at a glance.

**Comment by polinasok** [comment]
@eliben 

> It will avoid pushing too much vscode-specific logic into Delve.

Agreed that we want to avoid pushing anything vscode-specific into Delve. 
I believe so far we have been successful in avoid this, but please do let me know if you think otherwise.

> As of now, the LaunchRequestArguments interface contains a lot of information that's outside the spec of the DAP protocol. It's specific to how vscode invokes debug adapters.

The current debug adaptor also gets all these extra arguments and just ignores them. That configuration passes through all the layers, so I think the idea is to just capture all attributes in one place and to let each layer handle those that of interest to it. 

Since the arguments are a free-form map and not a struct, we do not have any of those vscode-specific fields coded anywhere. Are you concerned that they are polluting the request that delve receives even if it never reads those fields? Or do you think we should avoid having delve handle launch requests all-together and go back to specifying the program on the delve command line?

> If folks want to use Delve with other IDEs (which we already know is the case!) they will have to implement their own logic inside Delve or masquerade as vscode.

Do you know of a specific example where the current approach might cause issues? I have not looked into other IDEs very closely yet.

My general understanding is that launch.json-like configuration is of part of the contract, even if DAP spec does not specify it in detail. Some fields are editor-specific. Others are adapter-specific. So the adapter (and in our case delve) has to make it clear, which argument fields it relies on and vscode or any other IDE have to supply them in launch/attach requests. And how they source them from the user or internally (via launch.json or something else), will be up to each client.

> the existing debug adapter has some logic for finding Delve and prints out customized error messages if Delve is not found. It's not clear how easy this is when dlv is specified directly in package.json

Your concern about the dlv installation is very valid. I believe by default you get a "no debug adaptor" message, which is not very useful because the user would not know that delve is the adaptor and delve is missing and needs to be installed. However, if debugServer option is used, it [takes precedence](https://github.com/microsoft/vscode/blob/8ec6ec7dc128b949f445ba254eabc8e931e90f78/src/vs/workbench/api/common/extHostDebugService.ts#L817) over the executable in package.json, which is the very last [fallback](https://github.com/microsoft/vscode/blob/8ec6ec7dc128b949f445ba254eabc8e931e90f78/src/vs/workbench/api/common/extHostDebugService.ts#L856). So whatever extension code launches delve as an adapter and sets debugServer, can in theory do the same kind of error-checking and messaging that the current adapter does.

> Therefore, if we want vscode to talk directly to Delve without an adapter in between, we'll have to either ask users to have debugServer in each launch.json.

I tried to highlight in my [overview comment](https://github.com/golang/vscode-go/issues/23#issuecomment-641906002) that debugServer will be set in the extension code (goDebugConfiguration.ts). Looks like it was not clear that that we will not need any input from the user via launch.json (unless they want to debug an external adapter). Reworded a bit. Please let me know if it is still unclear.

**Comment by eliben** [comment]
@polinasok 

Thanks for updating the overview comment with all the options side by side; this is very helpful.

**Comment by eliben** [comment]
Regarding "thin adapter" vs. "no adapter", it's also worth pointing out that if we want to implement the `RunInTerminal` request, we may need to have an adapter. This came up in discussions with the Delve folks. The `RunInTerminal` reverse request is described in more detail in the *Launching And Attaching* section of the [DAP overview](https://microsoft.github.io/debug-adapter-protocol/overview).

This may help eventually resolve issues like #124

**Comment by hyangah** [comment]
@eliben @polinasok Thanks for keeping the overview up to date. I don't think directly communicating with DAP is an option. As @quoctruong pointed out in offline discussion, we already have vscode specific stuff. In LSP we handled it using a middleware and that gives us great flexibility (accessing information available in the extension host, translating vscode specific file paths, or dealing with bugs in the language server, etc). For DAP, I guess the thin adapter is the only option that provides such flexibility. 

I wonder if we can still aim at supporting both modes - to run it as an inlined implementation, and to run it as a separate process. 

Thanks for the pointer to `RunInTerminal`. That will be a huge improvement.

**Comment by polinasok** [comment]
More on [`RunInTerminal`](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal). It is a reverse request from the adapter that passes the debug command to the editor to start in the integrated or external terminal. It is used to allow for things like:
1. reading the program’s stdin
2. redirecting its stdout (which is otherwise mixed in with the messages from the client and the adaptor in the Debug Console)
3. giving access to a native command-line debugger interface from the terminal

The following related issues have been filed against vscode-go: https://github.com/microsoft/vscode-go/issues/843 (=https://github.com/golang/vscode-go/issues/124), https://github.com/Microsoft/vscode-go/issues/219, https://github.com/microsoft/vscode-go/issues/186, https://github.com/microsoft/vscode-go/issues/2204.

However, because of delve's [split frontend/backend architecture](https://speakerdeck.com/aarzilli/internal-architecture-of-delve?slide=33), this is not straightforward, which is likely why the current architecture does not yet support `RunInTerminal` in spite of having that extra layer that we intend to introduce with a lean adapter.  The issues listed above were closed with "based not the current state of delve, this feature is not doable". The only open issue #124 says "debug my go project at outside console" (3) and "support standard input" (1), so requesting the same things as the closed issues. 

The complication is that in delve's case, the frontend is a separate client from the server backend and is not launched when the backend connects to the vscode client. Perhaps, the --accept-multiclient feature can be adapted for this, but that would require reworking `dlv dap`, which currently assumes only one client at a time. Accessing stdin in delve is non-trivial as well (see https://github.com/go-delve/delve/issues/65, https://github.com/go-delve/delve/issues/1274).

**Comment by eliben** [comment]
> I wonder if we can still aim at supporting both modes - to run it as an inlined implementation, and to run it as a separate process.

I tried taking the existing debug adapter and making it "inline mode", executing in-process with the rest of the extension. This turned out to be pretty simple - [here's a commit from my branch where it was implemented](https://github.com/eliben/vscode-go/commit/81042e0e813f781bb0e5d6eeb747834bb21d6d97). I can verify that I can debug the extension and the DA in the same vscode session right now.

As far as I could figure out from digging in vscode's source, even in inline mode the `debugServer` setting in `launch.json` will still be respected, so we can still run the DA in a separate process if we want to.

We should probably move this discussion to a separate issue, though, since it's orthogonal to DAP.

**Comment by hyangah** [comment]
@eliben Agree that we discuss it in a separate issue https://github.com/golang/vscode-go/issues/232

For the DAP layer implementation, can we start merging the prototype so more users can play with it? 

BTW from @polinasok's [comment above](https://github.com/golang/vscode-go/issues/23#issuecomment-643467459) - it looks like the dap mode assumes only a single client. Isn't it problematic? I saw multiple users using the multiclient mode.

@quoctruong can you also take a look if @eliben's prototype and the current delve DAP meets the requirements for the cloud debugging use cases (remote, and attach)?

**Comment by polinasok** [comment]
@hyangah @quoctruong 
DAP-Delve is still work in progress and does not yet have the features to support remote debugging. I can work on that next if that helps, but neither local nor remote debugging will be fully supported until a number of other requests, applicable in both cases, are implemented.

As far as I know, vscode-go does not take advantage of delve's --accept-multiclient flag when starting delve. So must apply to the case when the debugger is started remotely. This requirement has not come up with our discussions with @quoctruong & his team before, but if this is critical please let us know.

**Comment by polinasok** [comment]
If I understand correctly, the new path inference mapping (#45) uses delve's RPCServer methods (ListSources and ListPackagesBuildInfo). Equivalent requests are not available under DAP, are they? It appears that we would need to upgrade the DAP protocol to support this via an adaptor in vscode-go. 

If delve supports the mapping, it could likely get the local side of the mapping via the launch/attach arguments. Those are the only implementation specific fields under DAP, so we are free to put whatever we want there without global changes to the protocol.

**Comment by polinasok** [comment]
@hyangah Unlike LSP case, I do not think the debug adaptor has direct access to extension host information. Having direct access to that state could be quite powerful. But I think at least the current version gets everything from the DAP requests.

**Comment by polinasok** [comment]
We must also be careful about handling noDebug case right. This logic does not belong in delve - the user should not need to install a debugger to skip debugging. This is currently done in the debug adapter, but one can also argue that an IDE could have language support for editing and running code without any debugging support, so this could potentially belong in the extension code. Do we know if there is precedent in other languages for this?

**Comment by hyangah** [comment]
@polinasok  Isn't `vscode.DebugAdapterDescriptorFactory` the place where we can switch between `dlv` for usual debug mode and handling of `noDebug` mode (passing `go run` or the output after `go build`)? I think significant part of logic currently in goDebug.ts should move to the factory. 

I have no good idea about the automated path inferring yet - I wonder if there is a way to teach vscode or the debug adapter to send a partial file path instead of the full path. Trim the local `GOROOT`, `GOPATH`, `GOMODCACHE` parts. 
And in case of ambiguous file names, ask users to provide explicit mappings and apply it by using `config substitute-path` or something equivalent, instead of trying hard to guess the path mapping by ourselves. @quoctruong

**Comment by hyangah** [comment]
Updates:
 - The experimental prototype thin adapter @eliben implemented is included in the extension.
 - @polinasok and @suzmue are making good progress in delve dap https://github.com/go-delve/delve/commits/master/service/dap 
 - @hyangah experimented with `RunInTerminal` prototype in the legacy debug adapter (https://go-review.googlesource.com/c/vscode-go/+/268461). We now have better understanding of the nature of such reverse requests.
 - We also experimented with starting `dlv dap` early to serve [`initialize`](https://go-review.googlesource.com/c/vscode-go/+/268460) (in the context of answering some open questions of [Option 2](https://github.com/golang/vscode-go/issues/23#issuecomment-641906002). 
-----

Based on our experiments, I want to propose some adjustments in the plan:

  **We want to eliminate the node.js-based thin adapter, and the extension will start a local `dlv dap` server for a debug session.
  The `dlv dap` can work like [Option 1](https://github.com/golang/vscode-go/issues/23#issuecomment-641906002) for simple   launch requests,  but can switch to [Option 2](https://github.com/golang/vscode-go/issues/23#issuecomment-641906002) mode depending on the  launch/attach request types.**

**Why?**

1. One less node.js program to maintain.
1. Directly launching `dlv dap` allows a cleaner initialization handshake process, and works efficiently for the most common scenario (case 1). 
1. Ability to switch to Option 2 allows us to implement "Reverse Requests" more naturally. Initially, we were thinking to implement the "Reverse Request" feature from the node.js thin adapter, but by implementing it inside `dlv dap`, the feature will be accessible by other editors easily, and help `dlv dap` more feature complete. 
1. We cannot reuse most of the current debug adapter's code for automated path mapping as it is now because it heavily depends on Delve's JSON-RPC. So, we have to reimplement it any way. Some of the tasks can be done more efficiently from `dlv dap` side. And this feature can be beneficial to other editors.
1. We cannot think of vscode-specific features that require implementaion inside the thin adapter yet. VS Code specific features the current DAP is implementing can be moved to `resolveDebugConfiguration` as @quoctruong  [commented](https://github.com/golang/vscode-go/issues/23#issuecomment-642113760). The current DAP predates most of the VSCode Debug APIs, that's why some of VS Code specific features leaked to the adapter. We already moved some to the extension side utilizing the `resolveDebugConfiguration`. If we ever need vscode-specific modification after the launch configuration is sent, that's a failure of the protocol spec. :-)

Disadvantages:
1. Inlining the adopter is no longer an option.
1. `dlv dap` has to support different modes of operations, and becomes more complex - but I hope switching to go makes it more accessible to a wider group of go developers.
1. `dlv dap` need to be able to communicate over stdin/stdout in addition to the network socket for better user experience.

**How?**

* Initialization

   - Extension will configure to launch a new `dlv dap` using `DebugAdapterExecutable` mode adaptor factory. VSCode and DelveDAP will communicate over `stdin/stdout`.

   ```
            VSCode   <=(stdin/out)=>  DelveDAP (main)
   ```

   - VSCode and DelveDAP complete the initial handshakes including the `initialize` request, and VSCode sends the `launch` request.

 * Case 1: Launch (local, `debug/test/exec` mode) without need for `RunInTerminal`

   ```
           VSCode   <=(stdin/out)=> DelveDAP === Debugee
   ``` 

   - If `noDebug` is false, DelveDAP will build (`debug/test`) and start Debugee for normal debug setup. If `noDebug` is true, DelveDAP will build (`debug/test`) and start the program (no ptracing).  Debugee uses DelveDAP's `stdin/stdout/stderr`, so its output will appear in the standard `DEBUG CONSOLE` along with other Delve DAP's logging/error messages.

* Case 2: Launch (local, `debug/test` mode) with need for `RunInTerminal`

  ```
         VSCode  <=(stdin/out)=> DelveDAP   <=(network socket)=> DelveDAP'  === Debugee 
  ```
   - Upon receiving a launch request, DelveDAP will issue a `RunInTerminal` request to the editor with the command to start DelveDAP'  (e.g. `-listen=localhost:<port>` etc). VSCode will open an integrated or external terminal, start DelveDAP' from the terminal, and send a response. 
   - DelveDAP' listens on the specified port, and the terminal's stdin/stdout/stderr will be accessible.
   - DelveDAP connects to DelveDAP` using the port, performs the handshake based on the information it learned from the prior handshake with VSCode. Then sends a modified launch request (to disable `RunInTerminal`). 
   - DelveDAP' starts* the Debugee. Debugee will use the terminal's stdin/stdout/stderr. 
   - DelveDAP's logging/error messages will print in the standard `DEBUG CONSOLE`.
   - DelveDAP' terminates upon receiving a Terminate/Disconnect request.
   - **Question**: Who is responsible for _building_ the Debugee binary? DelveDAP or DelveDAP'?
   - Note: if DelveDAP fails to initiate a proper teardown process for some reasons (e.g. crash), it's possible that DelveDAP' is not cleaned up. In that case, the user can manually terminate it with Ctrl+C, etc) 

* Case 3: Attach, Local: DelveDAP will `attach` to the existing process, so Debugee will have its own stdin/stdout/stderr. 

   ```
           VSCode   <=(stdin/out)=> DelveDAP ---- Debugee
   ``` 
  - Whether to terminate Debugee or not follows the DAP protocol.

* Case 4: Attach, Remote: DelveDAP connects to the remote `dlv dap` process (DelveDAP'').
   ```
          VSCode <=(stdin/out)=> DelveDAP <=(network socket)=> DelveDAP'' === Debugee
   ``` 
   -  Similar to case 2 except that DelveDAP does not launch DelveDAP''. 
   - DelveDAP'' may have different capabilities. During the initialization, if the difference is detected, DelveDAP may issue the updated capabilities events back to VSCode, or we may give up with warnings if it is too complicated (version mismatch?)
   - Whether to terminate Debugee or not follows the DAP protocol.
   - **Question**: How will the Debugee and the DelveDAP'' start? In the current workflow, users have an option to launch the debugee when starting the headless dlv server using `dlv exec/debug/test` command. On the other hand, `dlv dap` does not launch the debugee process until it receives the `Launch` request.

----

Note: We also found `--accept-multiclient` use case. Many users favor the full-featured dlv CLI to the limited DEBUG CONSOLE that depends on DAP's evaluate requests. For those users, we can make DelveDAP launch `DelveDAP'` in multiclient mode, and launch `dlv connect` using `RunInTerminal`.  One caveat is that `dlv connect needs Delve's JSON-RPC interface but the `delve dap` server does not support it. So, we need a way to make a delve server speak in both interfaces.

---

> Q. the existing debug adapter has some logic for finding Delve and prints out customized error messages if Delve is not found. It's not clear how easy this is when dlv is specified directly in package.json

In this new setup, VSCode will warn users properly if the dlv binary is not found. And, the extension will try to ensure the dlv binary exists and supply the right executable path through VSCode's [DebugAdapterDescriptorFactory](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterDescriptorFactory).

/cc @polinasok @eliben @quoctruong  @suzmue @aarzilli @derekparker

**Comment by polinasok** [comment]
@hyangah could you please comment as to why you think we need to have a DA connection over stdin/out? Since delve is designed to talk over a socket, that would require some major changes to delve and/or implementation of an extra layer.

Currently vscode offers us the following [debug adapter options](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/extension.ts#L26-L45):
1. an executable, communicating over stdin/out, launched and discarded with every debug session
2. a server, communicating over a socket
     A. single-use: server is terminated and restarted with each debug session
     B. multi-use: client connection is terminated and restarted with each debug session
3. inlined within the extension
4. [NEW] a server, communicating over named pipe/domain socket

> We cannot think of vscode-specific features that require implementation inside the thin adapter yet. VS Code specific features the current DAP is implementing can be moved to resolveDebugConfiguration

If we do not know of anything that must be in the thin  (TS or Go) adapter, then I propose that we, at least initially, consider **option 2 above and run dlv-dap as a server, communicating with the editor over a socket** and handling the full sequence of the debug session requests without any intermediaries. We can use [our version of `DebugAdapterDescriptorFactory` configuring the adapter as `DebugAdapterServer`](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/extension.ts#L80-L104) that would create the server (unless we were already given host/port by the remote attach mode) and connect to it in `createDebugAdapterDescriptor` from the extension. As the need for another layer evolves (e.g. status quo dlv-dap is released and we work on `RunInTerminal`), we can always insert it as needed, can't we?

The current dlv-dap server terminates itself with every disconnect request, so we would need to redo this for every debug session. But as we upgrade dlv-dap with more features, we can let the server survive beyond a single client connection and accept more connections. This ties nicely into supporting `--accept-multiclient` that we need to support `--continue` for remote mode and to support simultaneous connections from multiple clients, e.g. to take advantage of alternative UIs (like @hyangah suggestion to use `dlv connect` if we upgrade the server to speak both APIs).

In the single-use server case, the server will terminate itself on disconnect. We should use random ports to avoid any conflicts (see discussion in https://github.com/microsoft/debug-adapter-protocol/issues/126). In the multi-use server case, we should be able to terminate in `dispose` as shown in the [mock example](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/extension.ts#L80-L104). And we could use the same mechanism to clean up any rogue single-use servers that did not properly clean themselves up or check that the previous server is gone when we launch a new one. 

I have not prototyped this yet, so this is all theoretical. Plus my TypeScript familiarity is very superficial, so take my next suggestions with a grain of salt. I will revise them as I learn more. But for now I was thinking we could use the same spawn mechanism to launch the dlv-dap server process as we [currently do in `debugAdatper` to start headless dlv](https://github.com/golang/vscode-go/blob/5011235fd7c645e4a0e2ce4c977f80d586e72cce/src/debugAdapter/goDebug.ts#L565-L590), which allows us to register callbacks on close, error, etc. There is also the `net` module that gives us an asynchronous network wrapper. Seems like we need a way to detect and clean-up unresponsive servers.  **Are there additional lifetime management concerns here we need to think through?**

**Comment by polinasok** [comment]
I have confirmed with @weinand that to implement a single-use version of:
```
VSCode <=(dap over socket)=> DelveDap
```
we can:
- use `DebugAdapterDescriptorFactory` to start and connect to dlv-dap server ([example](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/extension.ts#L80-L104)) whenever a debug session is triggered
- spawn dlv-dap process ([example](https://github.com/golang/vscode-go/blob/5011235fd7c645e4a0e2ce4c977f80d586e72cce/src/debugAdapter/goDebug.ts#L565-L590))
- use random port and pass host+port to the `vscode.DebugAdapterServer` ([api](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterServer]))
- register the factory ([example](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/activateMockDebug.ts#L93))

If we make dlv-dap multi-use (able to accept multiple sequential client connections), we can change the factory to create it only for the first debug session, then just keep reconnecting to it for every new trigger, and then clean it up in `dispose()`, which is called when the extension is deactivated ([example](https://github.com/microsoft/vscode-mock-debug/blob/9174fca42890637ba5ed11ae18321f6f212d02c7/src/extension.ts#L99-L104)).

**Comment by hyangah** [comment]
dlv-dap is available from the stable extension for try.
https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md

Many details had changed this year. Since we passed the initial brainstorming and design stage, and most discussion happens outside this specific issue, I will close this.

There are still a few missing features and caveats, and we still have many tasks planned for polishing.
We will keep tracking of the remaining tasks for v0 in the project dashboard https://github.com/golang/vscode-go/projects/3
