### ISSUE TITLE
Gopls crashed in vscode and couldn't create connection to server

### ISSUE THREAD

**Issue by dle8** [golang/vscode-go#2300]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.18 darwin/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- `golang.org/x/tools/gopls master`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.68.1`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.34.0`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- 
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/dungtuanle/go
GOROOT: /usr/local/go
PATH: /Users/dungtuanle/go/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin

	go:	/usr/local/go/bin/go: go version go1.18 darwin/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/dungtuanle/go/bin/dlv	(version: v1.8.2 built with go: go1.18)
	staticcheck:	not installed
	gopls:	/Users/dungtuanle/go/bin/gopls	(version: (devel) built with go: go1.18)

go env
Workspace Folder (tools): /Users/dungtuanle/Desktop/tools
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/dungtuanle/Library/Caches/go-build"
	GOENV="/Users/dungtuanle/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/dungtuanle/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/dungtuanle/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.18"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/dungtuanle/Desktop/tools/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nk/vc539lw93856mchxslm_qds000y1hm/T/go-build1615749012=/tmp/go-build -gno-record-gcc-switches -fno-common"

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
{
    "go.languageServerFlags": ["-remote=localhost:8091"],
    "gopls": {
        "ui.diagnostic.analyses": {
            "unusedparams": true
        }
    }
}
```

### Describe the bug
Gopls couldn't create handshake when starting gopls server in vscode.

### Steps to reproduce the behavior:
1. Move to gopls directory and run `go run . -listen=localhost:8091`
2. Restart language server with `cmd+shift+p` -> `Go: Restart Language Server`
3. See error

### Screenshots or recordings
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/43080704/175094348-106d507d-2092-4fe4-ba78-f902e3feae89.png">

**Comment by hyangah** [comment]
The problem occurred because in the user's setup, gopls was running in a forwarder mode, so [`startLanguageServer`](https://github.com/golang/vscode-go/blob/fef5f147ffd7445bef0b6ecc1d47354c7aa940b8/src/goMain.ts#L105) failed when the daemon mode gopls was not yet available. Unfortunately the exception wasn't handled. As a result, [the `go.languageserver.restart` command registration](https://github.com/golang/vscode-go/blob/fef5f147ffd7445bef0b6ecc1d47354c7aa940b8/src/goMain.ts#L111) didn't run.

@jamalc already addressed this missing exception handling & command registration ordering issue in https://go-review.googlesource.com/c/vscode-go/+/413424, and this change is available in today's Nightly release.

However, I noticed another issue -

Now we are prompting various error messages (including the prompt for filing an issue), which is still a regression from v0.33.x. 

This needs fix.
