### ISSUE TITLE
Test.go unable to find specified package within $GOROOT or $GOPATH

### ISSUE THREAD

**Issue by black-fyr3** [golang/vscode-go#2378]
Hi, I'm not sure if this would be classified as a bug or simply an error (apologies) but after attempting to run my terraform test code I've come across this issue as follows:

```
webserver_test.go:7:2: cannot find package "github.com/gruntwork-io/terratest/tree/master/modules/http-helper" in any of:
	/usr/lib/go-1.18/src/github.com/gruntwork-io/terratest/tree/master/modules/http-helper (from $GOROOT)
	/home/ubuntu/go/src/github.com/gruntwork-io/terratest/tree/master/modules/http-helper (from $GOPATH)
FAIL	command-line-arguments [setup failed]
FAIL
```

I'm guessing this is because the specified package is unable to be found within the GOROOT and GOPATH, but I'm slightly confused as to how this can be passed in for it to work.

The specified file which contains my test.go is as follows:

```
package test

import (
	"fmt"
	"time"
	"testing"
	http_helper "github.com/gruntwork-io/terratest/tree/master/modules/http-helper"
	"github.com/gruntwork-io/terratest/tree/master/modules/terraform"
	"github.com/stretchr/testify/tree/master/assert"
)

func TestTerraformWebServerExample(t *testing.T) {
	// website::tag::2:: Construct the terraform options with default retryable errors to handle the most common
	// retryable errors in terraform testing.
	terraformOptions := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		// website::tag::1:: Set the path to the Terraform code that will be tested.
		TerraformDir: "../terratest2/webserver",

		Vars: map[string]interface{}{
			"region": "eu-west-1",
			"servername": "testwebserver",
		},
	})

	// website::tag::5:: Clean up resources with "terraform destroy" at the end of the test.
	defer terraform.Destroy(t, terraformOptions)

	// website::tag::3:: Run "terraform init" and "terraform apply". Fail the test if there are any errors.
	terraform.InitAndApply(t, terraformOptions)

	publicIp := terraform.Output(t, terraformOptions, "public_ip")

	url := fmt.Spring("http://%s:8080", publicIp)
	
	httpd_helper.HttpGetWithRetry(t, url, nil, 200, "I made a terrform Module!", 30, 5*time.Second)

}
```

I'm using an AWS Ubuntu VM (latest) running on amd64.

if there are any resources / documentation I could also look at would be greatly appreciated (I'm a complete newbie when it comes to go lang)

Much appreciated.

**Comment by hyangah** [comment]
The go command's error message is known to be misleading nowadays unless you are explicitly opting out of Go modules mode. 

Having `tree/master` in the module path looks unusual. That's likely an invalid module&package path.
For example, see https://github.com/gruntwork-io/terratest/blob/858fcf232269418ae4a292131373cb713a062d01/test/helm_basic_example_integration_test.go#L22

If your intention was to use a version currently in the master branch, download the master version using `go get`, e.g.,  
`go get github.com/gruntwork-io/terratest/http-helper@master` which will end up writing the version info in your main module's go.mod, and keep using the official module path from the source.

Good intro on modules https://go.dev/blog/using-go-modules
Tutorial series https://go.dev/doc/  
Module reference https://go.dev/ref/mod 

And, when you need help, here are the list of Go community - https://github.com/golang/go/wiki#the-go-community

Since this is not the vscode-go issue, I am closing this issue.
