### ISSUE TITLE
Run test doesn't work on package level

### ISSUE THREAD

**Issue by dzpt** [golang/vscode-go#2480]
Go work is released from 1.18.
However till now the `run test` button doesn't work on package level

### What version of Go, VS Code & VS Code Go extension are you using?
Vscode 1.69.1

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
go version go1.18.4 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
Build info
----------
golang.org/x/tools/gopls v0.8.4
    golang.org/x/tools/gopls@v0.8.4 h1:zGZsAXAb0LLws/Z+2BCWR17dkPHhIO2GYwYSSkeXX5c=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.11-0.20220513164230-dfee1649af67 h1:CJwk4qG1fov4WP7/DWhhb7OQVZlQKAl1rEMnDF+ceGU=
    golang.org/x/vuln@v0.0.0-20220503210553-a5481fb0c8be h1:jokAF1mfylAi1iTQx7C44B7vyXUcSEMw8eDv0PzNu8s=
    honnef.co/go/tools@v0.3.0 h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.4
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
1.69.1
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
Create a package and put test file insite, couldn't run it from there.
related to  #1763 

after click on run test, got  error `main module * does not contain package *`

**Comment by hyangah** [comment]
Based on the error message `main module * does not contain package *` I guess the package is outside the module, or the module is not listed in the go.work file.

For triage we need more info like
- go.mod, test file location
- if go.work is in use, does the go.work include the module where the package belongs to?

**Comment by dzpt** [comment]
@hyangah the package is a subfolder, here is the structure
```
package/
- util/
- - util_test.go -> test file is here
go.mod
go.work

```
`go.work` content
```
go 1.18
use .
```

`go.mod` content
```

module hello

replace util v1.0.0 => ./util

require (
	util v1.0.0
)
```

Its only work if i run go test from command, passing path on it.
`go test  -timeout 30s -v -run ^TestTokenizer util/ `

using `run test` button doesn't work
`go test  -timeout 30s -v -run ^TestTokenizer`

**Comment by hyangah** [comment]
Sorry that this issue fell through the cracks.

Unfortunately, I am not able to come up with a repro case with the given info.

From the last comment, `go.mod` content indicates the files in ./util belong to a separate module (so it can be used as a replacement of `util` module). If that's the case, `util_test.go` is indeed outside the main module (`hello`). However, `go test -timeout 30s -v -run ^TestTokenizer util/` indicates the package is in the main module. And `run test` button always runs from the package directory, so the module boundary shouldn't matter. 

From the discussion in https://github.com/golang/vscode-go/issues/1763, I think this error is related to unusual module arrangement. We need complete repro case (no missing `go.mod` files) to triage any further.

`go.testFlags` is for test flag values. Not for package paths. To check if the test can be runnable with the code lens,
go to the util directory, and from there run `go test -run ^TestTokenizer`. That should work.

This issue is more than a year old, and the go command and gopls support go.work and also provide better error messages. I hope you already figured out a better project structure to work with multiple modules, and this issue is no longer relevant. Otherwise, please either provide the complete example to repro or, try to run with the latest go version,

`cd ./util; go test -x -v`
