### ISSUE TITLE
tools: replace use of 'gopkgs' with 'go list all' 

### ISSUE THREAD

**Issue by marwan-at-work** [golang/vscode-go#258]
Currently, if you `cmd+shift+P` and choose `Go: Add Import`. The list of imported file looks incorrect. For example, packages within the same module do not show up. 

To reproduce, go into a module repo such as `golang.org/x/tools` and open a Go file such as `internal/lsp/source/rename.go`. 

Try to run the `Go: Add Import` and notice the list does not include most of the packages that you expect within the `tools` repo. Or even sometimes you get this error: 

```
Could not find packages. Ensure `gopkgs -format {{.Name}};{{.ImportPath}}` runs successfully.
```

As a solution, I don't think we have to call out into `gopkgs` anymore as we can just call `go list` directly to get all importable paths within a directory.

**Comment by hyangah** [comment]
Thanks @marwan-at-work for investigation and offering the fix. 

I want to know if I understand the issue right - since I can't reproduce the issue myself yet. Here is the screenshot.

![Screen Shot 2020-06-25 at 5 43 47 PM](https://user-images.githubusercontent.com/4999471/85798444-7db8ae80-b70b-11ea-9c86-287a27eda783.png)

What's the gopkgs version?
The version I am using is

$ go version -m ~/go/bin/gopkgs
/Users/hakim/go/bin/gopkgs: go1.14.3
        path    github.com/uudashr/gopkgs/v2/cmd/gopkgs
        mod     github.com/uudashr/gopkgs/v2    v2.1.2  h1:A0+QH6wqNRHORJnxmqfeuBEsK4nYQ7pgcOHhqpqcrpo=
        dep     github.com/karrick/godirwalk    v1.12.0 h1:nkS4xxsjiZMvVlazd0mFyiwD4BR9f3m6LXGhM2TUx3Y=
        dep     github.com/pkg/errors   v0.8.1  h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=

**Comment by marwan-at-work** [comment]
@hyangah 

```
marwansulaiman@Marwans-MBP go-proxy % go version -m `which gopkgs`
/Users/marwansulaiman/go/bin/gopkgs: go1.14.2
	path	github.com/uudashr/gopkgs/v2/cmd/gopkgs
	mod	github.com/uudashr/gopkgs/v2	v2.1.2	h1:A0+QH6wqNRHORJnxmqfeuBEsK4nYQ7pgcOHhqpqcrpo=
	dep	github.com/karrick/godirwalk	v1.12.0	h1:nkS4xxsjiZMvVlazd0mFyiwD4BR9f3m6LXGhM2TUx3Y=
	dep	github.com/pkg/errors	v0.8.1	h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
```

and here's what i get when trying to run the command: 

<img width="1386" alt="Screen Shot 2020-06-25 at 6 56 39 PM" src="https://user-images.githubusercontent.com/16294261/85803681-b8bfdf80-b715-11ea-9ac9-42ae1c20348b.png">

**Comment by hyangah** [comment]
@marwan-at-work thanks - interesting.

So, does `gopkgs -format '{{.Name}};{{.ImportPath}};{{.Dir}}' -workDir <the directory>` give you an error or the result missing  `x/tools/..` paths? Strange. 

Also confirm that you do not have any special settings enabled, and the extension is using the `gopkgs` `which gopkgs` returns. (fyi `Go: Locate Go Tools` command should give the absolute path to each tool binary). 

In general, I think switching to `go list` is a good idea (one less tool to depend on, and staying consistent with go build). But we need to understand the difference between them (performance and correctness wise). cc/ @uudashr

**Comment by uudashr** [comment]
Hi there, the reason why we create and use `gopkgs` is because of performance. At back day, there are no modules, so all the dependencies are goes to gopath and the package on gopath are always increasing.

Nowadays after I clean using `go list all` seems faster, due to the less packages on the gopath.

On my machine total packages on gopath and goroot 393
```
gopkgs  0.03s user 0.08s system 88% cpu 0.124 total
go list all  0.53s user 0.31s system 195% cpu 0.432 total
```

`go list all` still took longer, but seems still acceptable for user to wait.

**Comment by marwan-at-work** [comment]
I think https://github.com/golang/go/issues/48545 should close out this issue as well? cc: @hyangah

**Comment by jamalc** [comment]
This is finished with [CL 382457](https://golang.org/cl/382475).

**Comment by pavlelee** [comment]
`go list -f "{{.Name}};{{.ImportPath}}" all` is incomplete in go mod, nearly two-thirds less.

`go list -f "{{.Name}};{{.ImportPath}}" all`  
`gopkgs -format '{{.Name}};{{.ImportPath}};{{.Dir}}' -workDir ./`
