### ISSUE TITLE
Semantic token setting transition

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2598]
While addressing  https://github.com/golang/go/issues/54531 we realized semantic token feature should be controlled by `editor.semanticHighlighting.enabled` setting (https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#enablement-of-semantic-highlighting), not by the language server specific setting. 

Before the next gopls release, we need

* communicate clearly with users about this change
* help updating the configuration to unset this field
* update docs (https://github.com/golang/vscode-go/wiki/features#syntax-highlighting and https://github.com/golang/vscode-go#readme)

**Comment by seebs** [comment]
I noticed that one of the previous issues (2286) had a comment:

> gopls: allow semantic highlighting to work with large files #1387 @pjweinb can we close this issue now, since gopls is limiting the size of file?

1387 was a request to support doing partial ranges, rather than the full file, specifically to *work around* gopls limiting the size of the file, and to allow updates to parts of the file at a time.

but also note that gopls is software, and can be modified or configured, and may not always be limiting the size of the file.

as a user who sometimes has large files, i would definitely prefer that the extension use the partial-file range behavior to get semantic tokens rather than just giving up.

**Comment by pjweinb** [comment]
The vscode setting mentioned above (editor.semanticHighlighting.enabled ) does not seem to work, so closing this until there is a way for the client to control semantic tokens without setting a gopls flag.

**Comment by findleyr** [comment]
If this setting does not work, should we reopen #2286?
