### ISSUE TITLE
vet: warn about variable shadowing

### ISSUE THREAD

**Issue by mleonhard** [golang/vscode-go#270]
**Is your feature request related to a problem? Please describe.**
I need VSCode to warn about variable shadowing such as the line `x := 2` below:
```go
// example.go
package main

import (
	"fmt"
)

func main() {
	x := 1
	{
		x := 2              // Redefines 'x', shadowing the parent scope's 'x'.
		fmt.Printf("%v", x) // Prints '2'
	}
	fmt.Printf("%v", x)    // Prints '1'
	fmt.Printf("%v %v", 1) // A format string error.
}
```

**Describe the solution you'd like**
Add an option to execute `go vet -vettool=~/go/bin/shadow` in addition to `go tool vet`.  Use the correct path to the [`shadow`](golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow) binary.  If the `shadow` binary doesn't exist then offer to install it.

**Describe alternatives you've considered**
vscode-go supports the `go vet` command.

The `go vet` command no longer has a `-shadow` option ([golang/go#29260](https://github.com/golang/go/issues/29260)).

The `go vet` command supports alternative binaries with the `-vettool=BINARYPATH` option.  We can use the `shadow` binary to detect the error:
```
$ go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
go: found golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow in golang.org/x/tools v0.0.0-20200626171337-aa94e735be7f
$ go vet -vettool=/Users/user/go/bin/shadow example.go 
# command-line-arguments
./example.go:11:3: declaration of "x" shadows declaration at line 9
```
vscode-go accepts options to pass when running the vet program.  Unfortunately, vscode-go always runs the standard vet binary via `go tool vet`.  If we changed vscode-go to run `go vet`, then it could take the `-vettool=...` option.  But then it would run only the shadow variable check.  It would not run all of the other checks, such as the [printf check](https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md#printf) which validates format strings.

**Additional context**
![Screen Shot 2020-06-30 at 03 02 11](https://user-images.githubusercontent.com/520739/86114027-db882600-ba7e-11ea-8751-16b8883adc46.png)

**Comment by hyangah** [comment]
@mleonhard Thanks for reporting the issue.

After go 1.10, VS Code uses `go vet` instead of `go tool vet`. You can supply flags using `"go.vetFlags"`. One caveat is that the extension only runs one vet tool and specifying the `-vettool` flag will disable other default vet checks. Alternative approaches suggested are
  - write your own custom analyzer that does shadow checking + default checking and pass the tool to `-vettool`,
  - write a shell script that calls both `go vet` and `go vet -vettool=/path/to/shadow` and use `"go.alternateTools"` to invoke the script instead of `vet`, or
  - use tasks https://code.visualstudio.com/docs/editor/tasks

I see we need to update the configuration documentation (still mentioning `go tool vet`), and also fix the extension to output the error message when `go vet` fails due to invalid flags or missing vettool.

**Comment by kynefuk** [comment]
@hyangah 
> write a shell script that calls both go vet and go vet -vettool=/path/to/shadow and use "go.alternateTools" to invoke the script instead of vet, or

I tried to do this but, there is not error showing on problem tab.

My settings.json is following.
```
"go.alternateTools": {
    "vet": "${workspaceFolder}/govet.sh"
    "go vet": "${workspaceFolder}/govet.sh"
  }
```

Please point out any errors in my settings.json

**Comment by suzmue** [comment]
You can now enable the shadow analyzer in VS Code using:
```
"gopls": {
        "ui.diagnostic.analyses": {
            "shadow": true
        },
},
```

**Comment by kynefuk** [comment]
@suzmue 
It works for me!
Thanks a lot 👍🏿
