### ISSUE TITLE
Announcement mailing list for vscode-go

### ISSUE THREAD

**Issue by guettli** [golang/vscode-go#2773]
I read this from @findleyr:

we don't actually know what our users want: we only hear from users via surveys and issues,

I thought about this and i think the current situation could get improved.

I mean the communication between the authors and the users.

There are several options.

One could be an announcement mailing list (or newsletter). Then the authors could create surveys and inform us (the users) that they are looking for feedback. 

Of course the are several other options.

Please share your ideas, so that the authors get a better understanding of what users need.

What do you think about this?

**Comment by hyangah** [comment]
Thanks for the suggestion. 
The extension has been using welcome pages, release notes, readme, and prompt messages. Occasionally we've attempted to reach out more users through the gopher slacks, the issue tracker, and the discussion board. Opt-in telemetry is another option. We've been selecting different options depending on the features.

This issue is talking about one more communication channel.
When is it a good time to use the announcement mailing list instead of the existing communication channels?

**Comment by guettli** [comment]
I don't use the gopher slack (because they don't use threads). 

I don't actively follow the issue tracker or discussion board.

I read the release notes.

If you would create a survey, it is likely that I don't see your request for feedback. Which means it is unlikely that you get my feedback (except you use the release notes for that).

**Comment by hyangah** [comment]
Thanks. It sounds like announcement from the release notes.

**Comment by hyangah** [comment]
We discussed in our team meeting. We decided to utilize the existing communication channels more actively rather than creating a mailing list.

Release notes and blog posts will be our primary communication channels.
When need to communicate with a targeted group of audience and find appropriate, we will try to use prompts, too.

Thank you for the suggestion!
