### ISSUE TITLE
Breakpoint markers are small hollow gray circles instead of small red dots.

### ISSUE THREAD

**Issue by John-zhan** [golang/vscode-go#2780]
Breakpoint markers are small hollow gray circles instead of small red dots.
When the cursor moves to the small gray circle, the following prompt will pop up：

> "Couldn't` find statement at (marked breakpoint line .go file), please use a line with a statement"

![image](https://github.com/golang/vscode-go/assets/29363949/937dabf6-b3a6-42a5-a7c4-fabd873422dd)
![image](https://github.com/golang/vscode-go/assets/29363949/6f9b60bf-4ed1-4eba-b586-f542e0576174)

**Comment by hyangah** [comment]
The grey circle indicates the breakpoint couldn't be set because Delve (the Go debugger running behind the scene) couldn't find an instruction corresponding to the line 14. `var str = os.Args` is a statement so in debug mode that shouldn't happen... but, it looks like you were debugging with an optimized binary. (based on the "warning: optimized function..." message on the VARIABLES panel in the screenshot)

Can you please check if you built the binary with `-gcflags=all="-N -l"` flag? (https://github.com/golang/vscode-go/wiki/debugging#launch)

**Comment by John-zhan** [comment]
> The grey circle indicates the breakpoint couldn't be set because Delve (the Go debugger running behind the scene) couldn't find an instruction corresponding to the line 14. `var str = os.Args` is a statement so in debug mode that shouldn't happen... but, it looks like you were debugging with an optimized binary. (based on the "warning: optimized function..." message on the VARIABLES panel in the screenshot)
> 
> Can you please check if you built the binary with `-gcflags=all="-N -l"` flag? (https://github.com/golang/vscode-go/wiki/debugging#launch)

Thank u answerer, my built don’t have the gcflags

**Comment by John-zhan** [comment]
![image](https://github.com/golang/vscode-go/assets/29363949/c1ad12e3-0fcc-4331-b8af-8454e4219ac9)
Now I built my project with -gcflags=all="-N -l" flag, but now there still are some global variable that is gray circle

**Comment by suzmue** [comment]
Closing this as wai. If you run into other problems, please file another issue!
