### ISSUE TITLE
Extension performance issue

### ISSUE THREAD

**Issue by zeroidentidad** [golang/vscode-go#285]
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.15.0`
- OS Version: `Linux x64 4.15.0-88-generic`
- VSCode version: `1.46.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 38903,
		"activateCallTime": 238,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "golang.go",
				"_lower": "golang.go"
			},
			"activationEvent": "workspaceContainsTimeout:**/*.go"
		}
	},
	"runtimeErrors": []
}
```

**Comment by hyangah** [comment]
@zeroidentidad Please provide the details about the problems you are experiencing.

**Comment by zeroidentidad** [comment]
Maybe is related with hardware I have a laptop with Atom processor (my pc with i7 died :'v). I made configurations to speed up vscode but when I recently chage a last one option related with auto detect task it not says that extension take long time to initialize and extension host has stoped
![captura_1](https://user-images.githubusercontent.com/2924638/86709204-53a29e80-bfdf-11ea-8edf-5a15bdb58b61.png)

**Comment by hyangah** [comment]
@zeroidentidad @OneOfOne recently changed to bundle the extension (golang/vscode-go#53) - which means instead of reading in a couple of thousands of js files during initialization, now we need to read one js file. I see initialization time down from multiple hundreds ms to under a hundred ms on my machine. I am not sure if this will help in your case, but definitely worth giving a try. The pre-release version is released as golang.go-nightly. (https://marketplace.visualstudio.com/items?itemName=golang.go-nightly)  To use this you will need disable or uninstall the golang.go extension though.

Let us know if it helps.

**Comment by zeroidentidad** [comment]
I see, the performance improved a bit. Thank you :)

**Comment by hyangah** [comment]
@zeroidentidad thanks for the update. I will close this issue for now. If you find other issue or area to improve, please file a new issue. Thanks!
