### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by jsonpeng** [golang/vscode-go#2863]
gopls version: v0.12.4
gopls flags: 
extension version: 0.23.0
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@jsonpeng Thanks for the report. It looks like the extension version is pretty old. The latest extension version is v0.39.0.
Can you please update the Go extension? 

We've recently seen multiple users reporting the similar issues caused by a very old extension (v0.23.0). Can you please tell us more about how you install/update the extension? Many thanks!
