### ISSUE TITLE
gopls buildFlags docs seem wrong

### ISSUE THREAD

**Issue by aathan** [golang/vscode-go#2929]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.3 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls@v0.13.1 h1:Q0cfPbEG1WVfgxcRZ9uKTA6/ckIRNXx6Ym7KgT/VFE4=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
x64

* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
[here](https://github.com/golang/vscode-go/blob/master/docs/settings.md#settings-for-gopls) the docs seems to be wrong, as the correct setting in my `.vscode` file appears to be `gopls.buildFlags` not `gopls.build.buildFlags`

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by jamalc** [comment]
Could you share your config? go.buildFlags is distinct from gopls.build.buildFlags, is it possible that's what you're seeing?

**Comment by aathan** [comment]
```
{
    "go.toolsEnvVars": {},
    "editor.formatOnSave": true,
    "gopls.buildFlags": [
        "-mod=mod"
    ],
    "go.buildFlags": [
        "-mod=mod"
    ],
    "go.lintFlags": [
        "-mod=mod"
    ]
}
```

For sure `gopls.build.buildFlags` does not work but `gopls.buildFlags` does work. There have been other reports of this on stack exchange and/or in these issues (I forget exactly where I ran across those, but can go find if necessary).

**Comment by hyangah** [comment]
`build.buildFlags` is a 'gopls' setting.
It should be set like

```
"gopls": {
   "build.buildFlags": [ ... ]
}
```

`gopls.buildFlags` works *by accident* (since for gopls, `build.buildFlags` and `buildFlags` are aliases). It's not the path we are officially supporting.  See the following setting suggestions that reflect settings we are supporting.

![Screenshot 2024-01-09 at 11 36 13 PM](https://github.com/golang/vscode-go/assets/4999471/e5ee0dbd-ef0f-40ea-ae2f-e86472802c09)

![Screenshot 2024-01-09 at 11 37 19 PM](https://github.com/golang/vscode-go/assets/4999471/8ff392f5-084f-4d38-bca1-e5fd00353af2)

Closing.
