### ISSUE TITLE
Not able to install gopls and other tools on vs code , Installing golang.org/x/tools/gopls@latest FAILED, Error: Command failed: C:\Program Files\Go\bin\go.exe install -v honnef.co/go/tools/cmd/staticcheck@latest

### ISSUE THREAD

**Issue by sohanmh** [golang/vscode-go#3139]
### What version of Go, VS Code & VS Code Go extension are you using?
**go version go1.21.6 windows/amd64**
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="829" alt="image" src="https://github.com/golang/vscode-go/assets/156418848/4f8cbf8d-4a4a-4305-b613-5bc5269d83ce">

**Comment by hyangah** [comment]
Thanks for the report and the screenshot. Installation of these tools requires network access. Are you able to access `https://proxy.golang.org" from your machine? 

If not, depending on your situation, try one of the followings to workaround.

* If only access to proxy.golang.org is blocked:
   
Try in the setting `"go.toolsEnvVars": { "GOPROXY": "direct" }`. If you have other module proxy, you can set the proxy address instead of "direct". Reference: https://go.dev/ref/mod#communicating-with-proxies

* If network access is generally blocked or you are behind a firewall:

Find a proxy and set `HTTP_PROXY` and `HTTPS_PROXY` environment variables to point to the proxy server address.
Or talk to the network admin for help.

* If you can access proxy.golang.org, but VS Code cannot connect to it, manually run the commands for the tools installation. The error message includes `"cmd"` fields. Please run them from the terminal, and restart vscode.
