### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by sorenh** [golang/vscode-go#323]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

    [Error - 6:45:52 AM] Starting client failed
      Message: unsupported URI scheme:  (gopls only supports file URIs)
      Code: 0 
    gopls: failed reading header line: EOF

I'm using ms-vscode-remote.remote-ssh which is probably the reason why. I don't know where the bug report nor the fix belongs.

**Comment by hyangah** [comment]
@sorenh thanks for the issue report!
We received multiple of similar reports - did you try to open a single file? The current version of `gopls` doesn't support  single file edit yet; the next version will. https://github.com/golang/go/issues/39987#issuecomment-653312690 If that's the case, please try to open the directory where the file exists for now.

Otherwise, can you provide 
- your go extension settings
- how you launched your code and opened your workspace
- follow the instruction here https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code to capture the initial message exchange

**Comment by sorenh** [comment]
I can't seem to reproduce this anymore. I'm not sure what's different now. I'll close this and open a new report if I figure out how to trigger it.
