### ISSUE TITLE
Add Clear Language Server cache command

### ISSUE THREAD

**Issue by bancek** [golang/vscode-go#3245]
**Is your feature request related to a problem? Please describe.**
I copied a package `pkga` with file `pkga.go` to `pkgb`. The package in `pkga.go` remained `package pkga`. Then I created file `pkgb.go` inside `pkgb` with `package pkgb`. 

I got the error

```
found packages pkga (helpers.go) and pkgb (pkgb.go) in .../pkgb (go list)
package pkgb; expected pkga compiler(MismatchedPkgName)
```

When I removed the file `pkga.go`, the error remained. I guess `gopls` did not receive file deleted event for `pkga.go` and some cache in `gopls` did not invalidate.

I tried to remove the cache manually (`rm -Rf ~/Library/Caches/gopls/*`), restarted the Language server and reloaded the VS Code window and the error cleared.

**Describe the solution you'd like**
I would like to have a `Go: Clear Language Server cache` command that would clear all `gopls` caches (in-memory and on filesystem) for the workspace.

**Describe alternatives you've considered**
I've tried to remove the cache manually but it's difficult to do because there is no `Go: Stop Language Server` command and manual removing (`rm -Rf ~/Library/Caches/gopls/*`) races with Language Server restart.

**Additional context**
/

**Comment by findleyr** [comment]
Hi, it should never be necessary to clear the cache. The cache key should be a hash of all inputs into the cached calculation.

What you're experiencing is either (1) a bug in the cache, or (2) a corrupted state of the currently running gopls process, or (3) a broken state of the extension itself causing it to tell gopls inaccurate information. My bet 2 or 3, and here's how we can investigate:

- Does: `Go: Restart Language Server` fix your problem? If so, then you are experiencing 2.
- If not, does: `Developer: Reload Window` fix your problem? If so, then you are experiencing 3.

Otherwise, if the error persists, there may be a bug in our cache key.

I can say for certain that we would never want to add a command to clear the cache in order to work around corruption. We must fix the corruption.

CC @adonovan @hyangah

**Comment by bancek** [comment]
`Go: Restart Language Server` did not help (tried it multiple times). `Developer: Reload Window` fixed it, so most likely the state of the extension was broken. I cannot reproduce it, it happen under high CPU load and the extension probably missed the delete file event. `Go: Reset extension state` would be helpful here, but since `Go: Reload window` helps, it probably does not make sense to implement this.
