### ISSUE TITLE
Stack trace highlighting

### ISSUE THREAD

**Issue by myaaaaaaaaa** [golang/vscode-go#3518]
The Go Playground has a feature where any lines in a stack trace get highlighted in the editor:

![1725137246](https://github.com/user-attachments/assets/f4ff01a8-5a09-4a50-a683-4f86448e99ce)

Apologies if this is already implemented, I couldn't find anything through googling.

**Comment by hyangah** [comment]
@myaaaaaaaaa Unlike the playground that's meant to run the provided program, the extension does not run the analyzed program by default. Or do you mean the stack trace you'd encounter while running debugging or testing? The panic traces shown in tests or debugging are usually linkified so you can jump around directly click those links.

**Comment by myaaaaaaaaa** [comment]
> Or do you mean the stack trace you'd encounter while running debugging or testing?

Yes, I'm referring to how the Go playground seems to parse the stack trace, and highlights any line numbers that it finds

> The panic traces shown in tests or debugging are usually linkified so you can jump around directly click those links.

Stack traces have a tendency to grow excessively large and include irrelevant information (such as code in the standard library and third party dependencies).

In those situations, if the editor could highlight the lines that are part of the stack trace, it would be much easier for humans to process.

**Comment by hyangah** [comment]
>> The panic traces shown in tests or debugging are usually linkified so you can jump around directly click those links.
>
>Stack traces have a tendency to grow excessively large and include irrelevant information (such as code in the standard library and third party dependencies).
>
>In those situations, if the editor could highlight the lines that are part of the stack trace, it would be much easier for humans to process.

We discussed this in our team meeting.

We explored a similar idea when building UI for the vulnerability check result presentation which are function call stacks leading to the vulnerable symbols. But we abandoned it because we found the scattered diagnostics are harder to follow when multiple files and packages are involved. Unlike playground UI where there is a single page and often code for one file is present, editors work with multiple files shown in different tabs and buffers. The problem gets worse when the stack trace gets deeper and projects get complex. 

The lifetime of the visual error highlighting is unclear to me, too -  for example, when should we clear the highlight? When running multiple tests and multiple of them fail with stack traces, how do we want to highlight the code? etc.

Even though it's an interesting idea, I am not sure if we have time to explore this new UX and implement it. Sorry.
