### ISSUE TITLE
Go companion: test run creates duplicate test entries

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#3598]
* Go Companion version: v0.0.2.
* Go extension version: built from the master.

Repro:
  git clone https://github.com/robpike/ivy
  open vscode with the Go companion and VS Code Go extensions.
  
Settings:

```
    "go.enableCodeLens": {
        "runtest": false
    },
    "goExp.testExplorer.codeLens": "on",
    "goExp.testExplorer.showFiles": true,
    "goExp.testExplorer.nestSubtests": false,
    "goExp.testExplorer.nestPackages": true,
```

Before running the test.

![Screenshot 2024-11-11 at 1 40 41 PM](https://github.com/user-attachments/assets/fd78048a-f40d-4928-8fbe-746a30bb5e9a)

After running, dynamically discovered test was added under robpike.io/ivy node and created duplicate entries.

![Screenshot 2024-11-11 at 1 40 59 PM](https://github.com/user-attachments/assets/78259209-dfc2-4b4f-9b7e-1a4a11fb47f7)

cc @firelizzard18

**Comment by hyangah** [comment]
When this happens, the only way to recover is to reload the window. 
Would be nice if "Clear All Results" or an option removes all dynamically added tests and resets the explorer tree view.

**Comment by firelizzard18** [comment]
> Would be nice if "Clear All Results" or an option removes all dynamically added tests and resets the explorer tree view.

I should be able to attach dynamically added tests to a test run such that they can be cleared like that.

**Comment by hyangah** [comment]
I think the error is related to the fact that the entry in the root is a module, but also a package.

**Comment by firelizzard18** [comment]
Hitting refresh on the root will reset the tree to a degree. Specifically it purges the vscode test item tree, but not the Go test item tree. In this specific case, refreshing/reloading on the root does clear the duplicates. That could be a lot more obvious though I'm not sure how to make it so besides documentation.

The issue was not directly related to dynamic test items (also `TestQuoRem` does not appear to have subtests). I can go into more detail if you'd like but the TL;DR is that exposing `TestResolver.#getOrCreateAll` was a bad idea due to the fact that a given GoTestItem is not guaranteed to have a corresponding TestItem (e.g. the root package of a module).

**Comment by firelizzard18** [comment]
@hyangah Please verify this is fixed for you in https://github.com/firelizzard18/exp-vscode-go/commit/596df17c78e6f4ea2a0d2b7e0327747ab3d10848.
