### ISSUE TITLE
Include symbols from GOPATH

### ISSUE THREAD

**Issue by stingshen** [golang/vscode-go#430]
vscode-go has `gotoSymbol.includeGoroot` setting to control whether to include symbols form GOROOT. Is it possible for vscode-go to also include symbol form GOPATH? We can easily navigate through source code of different packages if we have this feature.

**Comment by hyangah** [comment]
Yes, you can access symbols from GOPATH - as long as they exist under GOPATH and you are not in [modules mode](https://github.com/golang/vscode-go/blob/master/docs/modules.md). In modules mode, symbols from module cache are accessible.

**Comment by stingshen** [comment]
Is it possible to access symbols from GOPATH in modules mode? We are heavily work in modules mode...

**Comment by hyangah** [comment]
In modules mode, GOPATH is less relevant except its module cache and not used by go command.
You can populate your module cache. Tools like gopls, goimports, and many of modules aware tools recognize packages and symbols if they are present in the module cache. 

`go build` and `gopls` will populate the module cache automatically in most cases. If you want to add modules to the cache your project doesn't depend on yet, you can download modules from the internet explicitly using `go get` or `go mod download` commands.

There could be edge cases since the modules mode and `gopls` are relatively new. If there are specific cases that do not work as you expected, please file an issue. It is easier to discuss over a specific feature and scenario.

**Comment by stingshen** [comment]
Hi hyangah,

Thank you for the answer! The issue may be related to the folder hierarchy. I can't `go to symbols` to the `third-party dependencies` if the go module is NOT in the root path of workspace. Is it the expected behavior?

Thanks,
Yi

**Comment by hyangah** [comment]
@stingshen Yes, that's the current limitation of `gopls`. See https://github.com/golang/vscode-go/issues/275.
It seems like @stamblerre and the gopls dev team is making some progress on recognizing module roots located in subdirectories. For now, the current workaround is to add the module roots manually separate workspace folders.

**Comment by stingshen** [comment]
@hyangah  Thank you for the confirmation!
