### ISSUE TITLE
ctrl + click on file shown in tab DEBUG OUTPUT  with compile error tries to find file with wrong fullpath

### ISSUE THREAD

**Issue by scottstensland** [golang/vscode-go#456]
Issue Type: <b>Bug</b>

a compile error happens to my source file however in DEBUG CONSOLE the offending bad source file is shown with correct fullpath however when I  (ctrl + click) on that file error message it tries to goto wrong nonexistent file

however in tabs OUTPUT and PROBLEMS  editor behaves OK 

Extension version: 0.15.2
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T15:51:39.791Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|11.58GB (3.14GB free)|
|Process Argv|--user-data-dir /home/ava/src/stenscode --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by scottstensland** [comment]
here is editor error on tab DEBUG CONSOLE

![vscode_compile_error_shows_wrong_filepath__DEBUG_CONSOLE](https://user-images.githubusercontent.com/60258/89122616-93518e80-d496-11ea-8f6c-2e2e0b622c2a.png)


however when showing tab OUTPUT all is well

![vscode_compile_error_shows_wrong_filepath__OUTPUT_tab](https://user-images.githubusercontent.com/60258/89122630-b54b1100-d496-11ea-8479-1f4c09e083f1.png)

**Comment by hyangah** [comment]
@scottstensland Do you have a custom `launch.json` configuration? 

Assuming you are using the default `launch.json` configuration, It looks like since the error message has `./main.go`, vscode tries to open the file from the project root directory. That resulted in a wrong file path.

Go Debug Adapter runs the program from the package directory. So, the file paths included in delve's output message need to be replaced with the right ones,  in order to teach vscode the right path.  Go test output handles the same problem here (https://github.com/golang/vscode-go/blob/c22bbe54ba13c1498f77a66f251bf868f7d1eacf/src/testUtils.ts#L445) 

cc @eliben 

The execution directory is determined inside the DebugAdapter  https://github.com/golang/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L376.  Stderr can be inspected and translated here https://github.com/golang/vscode-go/blob/c22bbe54ba13c1498f77a66f251bf868f7d1eacf/src/debugAdapter/goDebug.ts#L1728

In DebugAdapter2, it's determined in https://github.com/golang/vscode-go/blob/master/src/debugAdapter2/goDlvDebug.ts#L710.

**Comment by scottstensland** [comment]
I launch vscode from the terminal using

    code --user-data-dir ~/src/stenscode

and no that dir does not contain any file  `launch.json`
