### ISSUE TITLE
VSCode crash by Go

### ISSUE THREAD

**Issue by NhokCrazy199** [golang/vscode-go#469]
Issue Type: <b>Bug</b>

c:\Users\PhamK\.vscode\extensions\golang.go-0.16.0\dist\goMain.js:26315
    throw err;
    ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at c:\Users\PhamK\.vscode\extensions\766b.go-outliner-0.1.20\out\app.js:187:45
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Extension version: 0.16.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by hyangah** [comment]
@NhokCrazy199 Thanks for the bug report. 

It looks like the original exception was from the go-outliner extension (766b.go-outliner).

But the exception from other extension started to affect our extension since Go 0.16.0 release.
I think this is a side-effect of the inlined debug adapter. cc @eliben 

The code that threw an error is originated from [goDlvDebug.ts](https://github.com/golang/vscode-go/blob/c22bbe54ba13c1498f77a66f251bf868f7d1eacf/src/debugAdapter2/goDlvDebug.ts#L105):

```
process.on('uncaughtException', (err) => {
    const errMessage = err && (err.stack || err.message);
    vscode_debugadapter_1.logger.error(`Unhandled error in debug adapter: ${errMessage}`);
    throw err;
});
```
This is installing a process-wide uncaught exception handler.

It was packed in `goMain.js` probably because it's using inlined debug adapter factorin (https://github.com/golang/vscode-go/blob/c22bbe54ba13c1498f77a66f251bf868f7d1eacf/src/goMain.ts#L567). 

The dlv dap debug adapter is still in early stages, so I think it's better not to inline.
And when inlining, we should be aware of this process-wide exception handler.

**Comment by ivanovishado** [comment]
Hi, @hyangah. Is there any solution? Any way I can help? Is more info needed? Let me know, since this same error is happening to me.

**Comment by hyangah** [comment]
@ivanovishado thanks! In the mean time, roll back to 0.15.2. Extensions view -> Select "Go" extension -> Click the gear icon -> Install Another Version... -> Choose 0.15.2.

**Comment by ivanovishado** [comment]
Thanks, @hyangah!

**Comment by hyangah** [comment]
This is not yet released. Since this is a major bug, I will keep this open until it's released and verified.

**Comment by hyangah** [comment]
RC.1 is out. https://github.com/golang/vscode-go/releases/tag/v0.16.1-rc.1 

@NhokCrazy199 @ivanovishado @zhanswift Can you check if the RC1 addresses this issue? 
There is a link to the installation instruction. Many many thanks! 🙏

**Comment by ivanovishado** [comment]
@hyangah, I installed it and restarted Code several times. No issues so far. 👍

**Comment by hyangah** [comment]
Thanks all for verifying the fix. 0.16.1 is released.
