### ISSUE TITLE
open extract website , it's useless

### ISSUE THREAD

**Issue by nullfy** [golang/vscode-go#478]
![1596684534740](https://user-images.githubusercontent.com/13701882/89487466-1c8afd00-d7d8-11ea-9d20-992ce7b908ec.jpg)

**Comment by stamblerre** [comment]
@nullfy: I'm not sure I understand the issue here. Do you mind explaining what the problem is?

**Comment by hyangah** [comment]
@stamblerre I see a couple of issues from the screenshot. 

Peek Definition or Go to Definition on a package import path issues `textDocument/definition` request, and gopls returns all the files in the package.

I don't know vscode's selection algorithm when multiple Locations are returned, but most of times, it looks like it doesn't use the first one gopls returns, and chooses a wrong one.  I wonder if gopls can just return the Location where the package doc is present.

textDocument/documentLink may work better if the package doc can be served locally.

**Comment by stamblerre** [comment]
> Peek Definition or Go to Definition on a package import path issues `textDocument/definition` request, and gopls returns all the files in the package.
> 
> I don't know vscode's selection algorithm when multiple Locations are returned, but most of times, it looks like it doesn't use the first one gopls returns, and chooses a wrong one. I wonder if gopls can just return the Location where the package doc is present.

This is intentional. Not everyone follows the typical Go style, so we can't assume that documentation will only appear in one file. Even if we did, there's no guarantee that that's what the user was hoping to navigate to, so showing all of the files in the package allows them to make that choice.

I'm guessing the issue may be referring to the issue of Ctrl + Click triggering both go-to-definition and opening a link -- this behavior can be adjusted through the "importShortcut" setting. This will disable the links:

```json5
"gopls": {
    "importShortcut": "definition"
}
```

**Comment by nullfy** [comment]
thanks, it is effective
