### ISSUE TITLE
gopls: trigger signature help and autocompletion for function with parameters

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#49]
See additional details here: https://github.com/microsoft/vscode-go/issues/3007.

**Comment by hyangah** [comment]
As discussed in https://github.com/golang/vscode-go/issues/839, 
the following setting seems to enable autocompletion in snippet/accepted suggestion's placeholder.

```
"[go]": {
  "editor.suggest.snippetsPreventQuickSuggestions": false
}
```
![Screen Shot 2020-12-10 at 8 55 43 PM](https://user-images.githubusercontent.com/4999471/101851886-7014ab00-3b2a-11eb-8d20-e3851d87004d.png)

Since the repro example image included in the original issue in the old repo is no longer available, I don't know if this is all of the problems the original issue was about. @stamblerre @Limitless-loong   Can you please verify?

**Comment by stamblerre** [comment]
I think you're right that that setting addresses the problem, so I think this can be closed.
