### ISSUE TITLE
Use gopls rather than godoctor for extract refactorings

### ISSUE THREAD

**Issue by sorenh** [golang/vscode-go#518]
**Is your feature request related to a problem? Please describe.**
If a project uses go.mod mode, the extract refactorings don't work as it depends on godoctor which does not yet support modules.

**Describe the solution you'd like**
gopls now supports these extract refactorings. The vscode plugin should use that instead of godoctor.

**Describe alternatives you've considered**
There's work in progress to make godoctor support modules, but a) it has stalled and b) since gopls provides the functionality it makes sense to use that instead.

**Additional context**
The most recent releases(s?) of gopls has this functionality, so we should be able to safely rely on it.

**Comment by hyangah** [comment]
@sorenh thanks! Yes, that's the directory we are heading. I was told both extract function and extract variable features are available since [gopls v0.4.4](https://github.com/golang/tools/releases/tag/gopls%2Fv0.4.4).

Some prerequisite decision making necessary before transitioning to gopls

 - gopls refactoring feature is already available through `Code Action` -> `Command`. 
Do we want to keep `Go: Extract to function` and `Go: Extract to variable` commands?
Note: if shortcut or keybinding is necessary, [custom keybinding on code action](https://code.visualstudio.com/docs/getstarted/keybindings#_custom-keybindings-for-refactorings) is already possible. 

 - If the answer is yes,  we need to sort out https://github.com/golang/go/issues/40438.

 - If the answer is no, we need to disable (or remove) the commands when gopls is used. But without improvements in LSP (https://github.com/microsoft/language-server-protocol/issues/724, https://github.com/microsoft/language-server-protocol/issues/764, ...), it will be still somewhat different user experience. 

I am leaning towards dropping the commands and waiting for the LSP improvement.

/cc @joshbaum @stamblerre

**Comment by sorenh** [comment]
If I invoke the "Source Action" command, I'm told "No source actions available". What am I doing wrong? "gopls version" tells me I'm running version 0.4.4.

**Comment by stamblerre** [comment]
@sorenh: If you highlight a range of text, you should see a lightbulb appear with a suggestion to "Extract to function". Does that work?

**Comment by sorenh** [comment]
@stamblerre Nope. It does for e.g. Typescript (checked the vscode source).

**Comment by sorenh** [comment]
@stamblerre Er... Now it does. I have absolutely no clue what I changed. I opened the "Typescript" output as well as the "gopls" and "gopls (server)" outputs to see if that might give me some clues. When I looked at my own source code, the light bulb was there.

**Comment by sorenh** [comment]
@stamblerre I just tried with code-insiders. Didn't do anything at all and now it works. I'm so confused.

**Comment by stamblerre** [comment]
Hm..not sure what was going on there, but glad it works now!
@hyangah: Do we want to keep this issue open to track deprecating the existing commands or is this good to close?

**Comment by hyangah** [comment]
I will close this bug now and track the command migration separately.
