### ISSUE TITLE
Prepend terminal PATH when go.goroot is set

### ISSUE THREAD

**Issue by segevfiner** [golang/vscode-go#544]
**Is your feature request related to a problem? Please describe.**
When using `go.goroot` to set an alternate Go version for a specific workspace, the terminal still uses the default `PATH` which leads the `go` command in the terminal to point to the default Go installation.

**Describe the solution you'd like**
Set the `PATH` in the terminal. (In a similar way to what is done when using `Go: Choose Go Environment`?)

Of course, this needs to be careful not to mangle the `PATH`, it should only really prepend the version and that's it, not set the entire variable.

**Describe alternatives you've considered**
Having to keep setting it manually...

**Comment by hyangah** [comment]
@segevfiner I thought I fixed this long ago - unfortunately, it still needs the window reload. Or do you mean that the PATH should be mutated automatically when `go.goroot` is changed after the extension is activated?

**Comment by segevfiner** [comment]
I have workspace where I set `go.goroot` in the workspace settings, it applies to stuff run by the vscode-go extension itself, but not in the integrated terminal of VS Code, after VS Code reload or otherwise. At least that's what I'm seeing.

VS Code 1.48.0 on macOS 1.14.6
vscode-go 1.16.1

**Comment by hyangah** [comment]
Thanks. Strange that `go.goroot` is the one I use to choose different versions of go and [this code](https://github.com/golang/vscode-go/blob/6aa134d718d8896617c8db850c7cc7c5e39179e4/src/goInstallTools.ts#L376) that applies the PATH mutation should run before the go version statusbar is activated.
The go status bar has the right version of go, right?

Given that you are using macOS, I wonder if any of the conditions here (https://github.com/golang/vscode-go/blob/18eaf7efd7c98b4d4fa3b0e3d7cbea1560bdc90b/src/goEnvironmentStatus.ts#L304-L313) are true and prevent from applying the PATH mutation.

**Comment by segevfiner** [comment]
@hyangah https://github.com/microsoft/vscode/blob/33d79af3d8258f3a9d03c67252b3c433164b4146/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts#L59

**Comment by hyangah** [comment]
Thanks @segevfiner 
Indeed I've been using with 

```
    "terminal.integrated.shellArgs.osx": [
    ],
```

Maybe I misinterpreted the comment here https://github.com/microsoft/vscode/issues/99878#issuecomment-642808852
and we should've sent the export command if '-l' is set (i.e. true for macos by default :-()

**Comment by burdiyan** [comment]
This fix completely broke my workflow with multiple Go versions for different workspaces.

I'm using Nix package manager and nix-shell + direnv for settings specific to projects. So I have one Go version installed globally with Nix and another one set with nix-shell for my project. It was working fine (because by default VS Code by default adds '-l' to shell arguments) for integrated terminal and PATH mutation was not invoked.

But now it mangles my PATH and overrides any Go version I've set in PATH with `direnv` by prepending my global Go version to my PATH.

I don't know why this is needed at all, why can't the extension just use whatever Go version is in the PATH without mutating it?

**Comment by segevfiner** [comment]
Maybe it shouldn't do this when `go.goroot` is unset...

**Comment by burdiyan** [comment]
@segevfiner  would be lovely!
