### ISSUE TITLE
Extension completely broken

### ISSUE THREAD

**Issue by oliverjanik** [golang/vscode-go#552]
OS: Windows
Go: 1.15
VSCode: 1.48.0

Steps:
1) Uninstall/ Reinstall go extension
2) create a main.go file
3) Autocomplete does not work
4) Format on save eats characters.

![image](https://user-images.githubusercontent.com/2280140/90727209-3bc07900-e306-11ea-99a5-d321bd61d9a4.png)

This extension has been very very flaky lately, maybe since Google took over from Microsoft?

It used to be my go environment but I can't recommend this to any new developer at the moment. Developer experience is **bad**. Every few weeks I check on this things are broken one way or the other.

**Edit**:
After running Go: Install/Update tools and reinstalling everything. the situation has improved.

Are there any logs to diagnose or to submit against github issues?

**Comment by hyangah** [comment]
From the list in the autocomplete suggestion in the screenshot, it doesn't look like the extension was activated. 

When the extension failed to start
  - VS Code will popup a message
  - Run the  "View: Toggle Output" command -> `Log (Extension Host)` menu

**Comment by rmasci** [comment]
I am having issues with autocomplete also, it's been hit or miss. I recently purged everything vscode on my system. then I reinstalled. Autocomplete is hit and miss, and will NOT autocomplete. Yes it says Go 1.15 in the status bar at the bottom right, the plugin is activated, all tools are installed. Kinda frustrated as my time is split between support and development I don't have the time to keep monkeying with VSCode settings. It just needs to work.  Spent an  hour this morning non-productive working on VSCode.

**Comment by hyangah** [comment]
@rmasci Please file an issue with the details (vscode settings, and example for the problem). The issue template has list of information necessary for investigation.

**Comment by rmasci** [comment]
Issue fixed. Autocomplete wasn't working. So I uninstalled, purged all vscode settings Used an uninstaller called "AppCleaner" that looks for all files associated with VSCode and deletes them. So now its like VSCode was never installed. Download the latest version, Fired it up, opened a go program I am working on. No autocomplete. OK So I head over to extensions Install  "Rich Go Language Support...". Reload vscode -- Autocomplete still is not working. Says "Go 1.15" in the bottom left status bar.  Highlighting is working fine, autocomplete not so much. 

How I fixed it. Shut down VSCode, Looked up the variable for GOBIN. Went to that directory and removed all the go tools, see list below. Restarted vscode, now it asks me to install the tools.  So recently I updated from go 1.14 to go 1.15 -- the auto complete continued to work because I believe gocode runs as a daemon, and I leave vscode up and running for days on my computer. So a day or so later when I had logged out and back in, restarted vscode -- autocomplete didn't work. So if the extension is go version specific, then it should have a means of testing those tools, and prompting you for a reinstall. Or at least something in the extension settings at the top that a user can click on "Reinstall Go Tools" -- maybe this is there but I certainly looked for it and missed it. 
List of Go Tools to delete from $GOBIN
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint

**Comment by rmasci** [comment]
Oh I can't just leave the comment without saying Thank you all for your work on this.  When it works -- it's brilliant and makes my coding so much easier, and I didn't have to sell my firstborn to buy Goland.

**Comment by hyangah** [comment]
@rmasci thanks for sharing how you fixed it. When the go version change is detected, the extension pops up a message about the tools need to be recompiled.  I think the heuristic it's using to detect the version change should be improved.

**Comment by oliverjanik** [comment]
I'm going to close this, purging and reinstalling all go tools, fixed most of my issues.
