### ISSUE TITLE
launch.json configuration: allow to setup buildFlags attribute dynamically

### ISSUE THREAD

**Issue by d2r2** [golang/vscode-go#564]
### What version of Go, VS Code & VS Code Go extension are you using?

* Run go version to get version of Go
  * go version go1.15 linux/amd64
* Run code -v or code-insiders -v to get version of VS Code or VS Code Insiders
  * 1.48.0
  * db40434f562994116e5b21c24015a2e40b2504e6
  * x64
* Check your installed extensions to get the version of the VS Code Go extension
  * v0.16.1

### Describe the bug

I've spent some time trying to find a way how to setup `buildFlags` attribute with well known golang cli workflow "how to assign variable from outside with template (with dynamically generated value)":
`go build -ldflags='-X main.version=<dynamically generated value>'`

With launch.json it works fine with a static value, like this:
```
{
            "buildFlags": "-ldflags='-X main.version=0.3.1'",
}
```

It almost works with variable assignment (but still generate empty value):
```
{
            "env": {
                "app_ver": "0.3.1",
            },
            "buildFlags": "-ldflags='-X main.version=${env:app_ver}'",
}
```

Ideally, it would be good to get value from preliminary executed shell script (extract last git tag + git commit hash) and then assign resulting value to variable or directly to buildFlags, like this:
```
{
            "env": {
                "app_ver": "<value obtained from external shell script or command>",
            },
            "buildFlags": "-ldflags='-X main.version=${env:app_ver}'",
}
```

Same thoughts are relevant to dynamically generated golang build tags. Perhaps I didn't find how to implement this, and there is such a possibility?

**Comment by hyangah** [comment]
@d2r2 Most of launch.json processing and its variable substitution is handled by VS Code https://code.visualstudio.com/docs/editor/debugging#_variable-substitution. So, please file an issue for help in the upstream repo (https://github.com/microsoft/vscode/issues).

```
{
            "env": {
                "app_ver": "0.3.1",
            },
            "buildFlags": "-ldflags='-X main.version=${env:app_ver}'",
}
```

It looks like the above didn't work as hoped because the `app_ver` env var defined in the same `launch.json` was set when vscode tries to resolve `"buildFlags"` by substituting `${env:app_ver}`. Referencing already existing env vars seems to work. I don't know if that's a bug or not. 

Another approach I want to mention is instead of the `launch.json` that's designed more towards launching debug processes, you can look into `task.json` that allows to run arbitrary scripts you like. Maybe you can define a custom build task, and then, configure launch.json to use the built binary (mode: exec).

**Comment by d2r2** [comment]
@hyangah, you was right - it works good when referencing global environments. I thought buildFlags is some specific option for vscode-go only (not upstream). I will look further and if it makes sense I will create upstream bug.

And thanks for the hint "mode:exec", I've made compilation working via task runner finally!

I will close this request, if you didn't mind. Thanks a lot!
