### ISSUE TITLE
Gopls update banner displaying despite setting `"go.useGoProxyToCheckForToolUpdates": false`

### ISSUE THREAD

**Issue by LukeWood** [golang/vscode-go#673]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- N/A using Theia-ide on ssh.cloud.google.com
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.16
- Run `go env` to get the go development environment details
```
lukewood@cloudshell:~$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lukewood/.cache/go-build"
GOENV="/home/lukewood/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lukewood/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build715618316=/tmp/go-build -gno-record-gcc-switches"
```

### Describe the bug
Gopls update banner displaying despite setting `"go.useGoProxyToCheckForToolUpdates": false`

### Steps to reproduce the behavior:
1. Go to ssh.cloud.google.com
2. run `go get  golang.org/x/tools/gopls`
3. See banner running

We set go.useGoProxyToCheckForToolUpdates for you to false

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/12191303/93817181-cce08380-fc15-11ea-820e-831d3a980417.png)

**Comment by LukeWood** [comment]
if this is a known issue and we must update to `0.17` please just let me know!

**Comment by hyangah** [comment]
@LukeWood I am not familiar with cloudshell IDE and I even don't know how to turn on the language server (No `go.useLanguageServer` setting is allowed and from the behavior, I am *guessing* gopls is not enabled by default?).

From your repro scenario, I noticed you installed gopls in the default mode. In order to retrieve the right version info, it needs to be installed in the modules mode. 

`GO111MODULE=on go get golang.org/x/tools/gopls` from a directory outside of any go module. 

If it doesn't get any version info, the extension is going to assume the gopls is ancient even without checking go proxy. And, each extension is released with a minimum required gopls version so if the gopls is too old, it will still pop up the notification when gopls seems too old.

**Comment by hyangah** [comment]
@LukeWood Let us know if installing a recent version of gopls in modules mode addresses the issue.

**Comment by LukeWood** [comment]
Aye - will do tomorrow.

**Comment by LukeWood** [comment]
hey there @hyangah I got around to testing this and it works.

Thanks for the help!

**Comment by LukeWood** [comment]
I reopened this because we are setting the setting to disable the banner, so I'm wondering:
Shouldn't this not show the banner regardless of the GO1111MODULE=on environment variable being set?  Or do I misunderstand

**Comment by stamblerre** [comment]
I'm sorry I'm not sure I understand your question. I don't believe the `GO111MODULE` setting affects this pop up. I believe @hyangah mentioned `GO111MODULE` above because it needs to be set to `on` to use the `path@version` syntax with the `go get` command, but that doesn't affect the pop-up, that just affects the way `gopls` is downloaded.

**Comment by LukeWood** [comment]
ah I see, that makes more sense.  It seems that I didn't fully understand the relationship there.

Well, either way I can't reproduce anymore.  So it seems the settings is being respected at this point, thanks for all of your help!
