### ISSUE TITLE
Linter diagnostic message should use correct linter name instead of always "go-lint"

### ISSUE THREAD

**Issue by golopot** [golang/vscode-go#948]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.5 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.18.1
- Run `go env` to get the go development environment details
	- irrelevant

### Share the Go related settings you have added/edited
```
    "go.useLanguageServer": true,
    "go.lintTool": "staticcheck",
```

### Describe the bug
When `lintTool` is set to `staticcheck`, the diagnostic message should be formatted as `Some error message (staticcheck)` instead of `Some error message (go-lint)`

### Steps to reproduce the behavior:
1. Set linter to staticcheck
2. Read one diagnostic message
3. Notice that the message use the incorrect name `go-lint`

#### Expected:
![1](https://user-images.githubusercontent.com/16285118/99787095-4505ef80-2b5a-11eb-9294-bc7192cb333d.png)

#### Actual:
![2](https://user-images.githubusercontent.com/16285118/99787107-4800e000-2b5a-11eb-8796-bbd854b46e11.png)

**Comment by hyangah** [comment]
I think that is the diagnostic collection name set here in 
https://github.com/golang/vscode-go/blob/2f0623c7ca65fd79e83c26ec37ce3832b2b271a9/src/goMain.ts#L150

I guess the intention was to differentiate among errors detected by go compiler, lint tool, and vet tool. Are you suggesting that it should be the individual tool's name rather than the kind of the tool?

**Comment by stamblerre** [comment]
On a somewhat related note, if you enable `staticcheck` through `gopls` (`"gopls": { "staticcheck": true }`), you will see `staticcheck` as the source.

**Comment by golopot** [comment]
> Are you suggesting that it should be the individual tool's name rather than the kind of the tool?

Yes. When people tries to fix a linter problem, it helps if they are told which linter produces the message.

**Comment by hyangah** [comment]
@stamblerre @golopot If the extension's own lint check starts using `staticcheck` to pick up non-default checks and the user is also using gopls with the `staticcheck` enabled, this would create confusion, wouldn't it?

Since users can choose only one linter, I feel using `go-lint` isn't too confusing. But if showing the specific tool name is desirably, should we go with `lint(staticcheck)` or something more verbose to avoid confusion?

**Comment by stamblerre** [comment]
> @stamblerre @golopot If the extension's own lint check starts using `staticcheck` to pick up non-default checks and the user is also using gopls with the `staticcheck` enabled, this would create confusion, wouldn't it?

We have been recommending people disable `go.lintOnSave` with `gopls` just because `golint` is going to be deprecated and `gopls` has the staticcheck support. Maybe we could check a user's settings to avoid duplication (disabling `lintOnSave` automatically if `gopls` with `staticcheck` or `golint` is enabled)?

**Comment by hyangah** [comment]
https://github.com/microsoft/vscode-go/issues/2100 is the history of how these diagnostic collections were named. According to the description, the diagnostics collection name is used by vscode in deduplicating diagnostics from extensions and task frameworks.

AFAIK, there is no official `go-lint` problem matchers yet (only `go` https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/workbench/contrib/tasks/common/problemMatcher.ts#L1311), but we need to double check the implication before changing it for cosmetic reasons. 

@segevfiner @ramya-rao-a for advice.
